# Issue 26280: py3: more trivial fixes to sage.rings.polynomial.polydict

archive/issues_026043.json:
```json
{
    "assignees": [],
    "body": "<div id=\"comment:0\"></div>\n\n\n\nComponent: **python3**\n\nAuthor: **Erik Bray**\n\nBranch/Commit: **[`4d7aa64`](https://github.com/sagemath/sagetrac-mirror/commit/4d7aa64eec851873106dbd14d0944b9bcda8271b)**\n\nReviewer: **Travis Scrimshaw**\n\n_Issue created by migration from https://trac.sagemath.org/ticket/26280_\n\n",
    "closed_at": "2018-09-19T07:52:39Z",
    "created_at": "2018-09-14T10:16:32Z",
    "labels": [
        "https://github.com/sagemath/sage/labels/c%3A%20python3",
        "https://github.com/sagemath/sage/labels/p%3A%20trivial%20/%205",
        "https://github.com/sagemath/sage/labels/bug"
    ],
    "milestone": "https://github.com/sagemath/sage/milestones/sage-8.4",
    "reactions": [],
    "repository": "https://github.com/sagemath/sage",
    "title": "py3: more trivial fixes to sage.rings.polynomial.polydict",
    "type": "issue",
    "updated_at": "2018-09-19T07:52:39Z",
    "url": "https://github.com/sagemath/sage/issues/26280",
    "user": "https://github.com/embray"
}
```
<div id="comment:0"></div>



Component: **python3**

Author: **Erik Bray**

Branch/Commit: **[`4d7aa64`](https://github.com/sagemath/sagetrac-mirror/commit/4d7aa64eec851873106dbd14d0944b9bcda8271b)**

Reviewer: **Travis Scrimshaw**

_Issue created by migration from https://trac.sagemath.org/ticket/26280_





---

archive/issue_events_359496.json:
```json
{
    "actor": "https://github.com/embray",
    "created_at": "2018-09-14T10:16:32Z",
    "event": "milestoned",
    "issue": "https://github.com/sagemath/sage/issues/26280",
    "milestone_number": null,
    "milestone_title": "sage-8.4",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/26280#event-359496"
}
```



---

archive/issue_events_359497.json:
```json
{
    "actor": "https://github.com/embray",
    "created_at": "2018-09-14T10:16:32Z",
    "event": "labeled",
    "issue": "https://github.com/sagemath/sage/issues/26280",
    "label": "https://github.com/sagemath/sage/labels/c%3A%20python3",
    "label_color": "0000b0",
    "label_name": "c: python3",
    "label_text_color": "ffffff",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/26280#event-359497"
}
```



---

archive/issue_events_359498.json:
```json
{
    "actor": "https://github.com/embray",
    "created_at": "2018-09-14T10:16:32Z",
    "event": "labeled",
    "issue": "https://github.com/sagemath/sage/issues/26280",
    "label": "https://github.com/sagemath/sage/labels/p%3A%20trivial%20/%205",
    "label_color": "fff9e5",
    "label_name": "p: trivial / 5",
    "label_text_color": "ffffff",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/26280#event-359498"
}
```



---

archive/issue_events_359499.json:
```json
{
    "actor": "https://github.com/embray",
    "created_at": "2018-09-14T10:16:32Z",
    "event": "labeled",
    "issue": "https://github.com/sagemath/sage/issues/26280",
    "label": "https://github.com/sagemath/sage/labels/bug",
    "label_color": "d73a4a",
    "label_name": "bug",
    "label_text_color": "ffffff",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/26280#event-359499"
}
```



---

archive/issue_events_359500.json:
```json
{
    "actor": "https://github.com/embray",
    "created_at": "2018-09-14T10:16:41Z",
    "event": "labeled",
    "issue": "https://github.com/sagemath/sage/issues/26280",
    "label": "https://github.com/sagemath/sage/labels/needs%20review",
    "label_color": "7fff00",
    "label_name": "needs review",
    "label_text_color": "ffffff",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/26280#event-359500"
}
```



---

archive/issue_events_359501.json:
```json
{
    "actor": "https://github.com/tscrim",
    "created_at": "2018-09-15T05:30:24Z",
    "event": "unlabeled",
    "issue": "https://github.com/sagemath/sage/issues/26280",
    "label": "https://github.com/sagemath/sage/labels/needs%20review",
    "label_color": "7fff00",
    "label_name": "needs review",
    "label_text_color": "ffffff",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/26280#event-359501"
}
```



---

archive/issue_events_359502.json:
```json
{
    "actor": "https://github.com/tscrim",
    "created_at": "2018-09-15T05:30:24Z",
    "event": "labeled",
    "issue": "https://github.com/sagemath/sage/issues/26280",
    "label": "https://github.com/sagemath/sage/labels/positive%20review",
    "label_color": "dfffc0",
    "label_name": "positive review",
    "label_text_color": "ffffff",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/26280#event-359502"
}
```



---

archive/issue_comments_405266.json:
```json
{
    "body": "Reviewer: **Travis Scrimshaw**",
    "created_at": "2018-09-15T05:30:24Z",
    "formatter": "markdown",
    "issue": "https://github.com/sagemath/sage/issues/26280",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/26280#issuecomment-405266",
    "user": "https://github.com/tscrim"
}
```

Reviewer: **Travis Scrimshaw**



---

archive/issue_comments_405267.json:
```json
{
    "body": "<div id=\"comment:2\" align=\"right\">comment:2</div>\n\nLGTM.",
    "created_at": "2018-09-15T05:30:24Z",
    "formatter": "markdown",
    "issue": "https://github.com/sagemath/sage/issues/26280",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/26280#issuecomment-405267",
    "user": "https://github.com/tscrim"
}
```

<div id="comment:2" align="right">comment:2</div>

LGTM.



---

archive/issue_comments_405268.json:
```json
{
    "body": "<div id=\"comment:3\" align=\"right\">comment:3</div>\n\n\n```\nFile \"src/sage/rings/polynomial/polydict.pyx\", line 982, in sage.rings.polynomial.polydict.ETuple.__init__\nFailed example:\n    ETuple(iter([2, 3, 4]))\nExpected:\n    Traceback (most recent call last):\n    ...\n    TypeError: Error in ETuple((), <list... object at ...>, None)\nGot:\n    <BLANKLINE>\n    Traceback (most recent call last):\n      File \"/home/sage-patchbot/sage/local/lib/python2.7/site-packages/sage/doctest/forker.py\", line 650, in _run\n        self.compile_and_execute(example, compiler, test.globs)\n      File \"/home/sage-patchbot/sage/local/lib/python2.7/site-packages/sage/doctest/forker.py\", line 1061, in compile_and_execute\n        exec(compiled, globs)\n      File \"<doctest sage.rings.polynomial.polydict.ETuple.__init__[3]>\", line 1, in <module>\n        ETuple(iter([Integer(2), Integer(3), Integer(4)]))\n      File \"sage/rings/polynomial/polydict.pyx\", line 1007, in sage.rings.polynomial.polydict.ETuple.__init__ (build/cythonized/sage/rings/polynomial/polydict.c:13297)\n        self._length = len(data)\n    TypeError: object of type 'listiterator' has no len()\n```",
    "created_at": "2018-09-15T22:41:32Z",
    "formatter": "markdown",
    "issue": "https://github.com/sagemath/sage/issues/26280",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/26280#issuecomment-405268",
    "user": "https://github.com/vbraun"
}
```

<div id="comment:3" align="right">comment:3</div>


```
File "src/sage/rings/polynomial/polydict.pyx", line 982, in sage.rings.polynomial.polydict.ETuple.__init__
Failed example:
    ETuple(iter([2, 3, 4]))
Expected:
    Traceback (most recent call last):
    ...
    TypeError: Error in ETuple((), <list... object at ...>, None)
Got:
    <BLANKLINE>
    Traceback (most recent call last):
      File "/home/sage-patchbot/sage/local/lib/python2.7/site-packages/sage/doctest/forker.py", line 650, in _run
        self.compile_and_execute(example, compiler, test.globs)
      File "/home/sage-patchbot/sage/local/lib/python2.7/site-packages/sage/doctest/forker.py", line 1061, in compile_and_execute
        exec(compiled, globs)
      File "<doctest sage.rings.polynomial.polydict.ETuple.__init__[3]>", line 1, in <module>
        ETuple(iter([Integer(2), Integer(3), Integer(4)]))
      File "sage/rings/polynomial/polydict.pyx", line 1007, in sage.rings.polynomial.polydict.ETuple.__init__ (build/cythonized/sage/rings/polynomial/polydict.c:13297)
        self._length = len(data)
    TypeError: object of type 'listiterator' has no len()
```



---

archive/issue_events_359503.json:
```json
{
    "actor": "https://github.com/vbraun",
    "created_at": "2018-09-15T22:41:32Z",
    "event": "unlabeled",
    "issue": "https://github.com/sagemath/sage/issues/26280",
    "label": "https://github.com/sagemath/sage/labels/positive%20review",
    "label_color": "dfffc0",
    "label_name": "positive review",
    "label_text_color": "ffffff",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/26280#event-359503"
}
```



---

archive/issue_events_359504.json:
```json
{
    "actor": "https://github.com/vbraun",
    "created_at": "2018-09-15T22:41:32Z",
    "event": "labeled",
    "issue": "https://github.com/sagemath/sage/issues/26280",
    "label": "https://github.com/sagemath/sage/labels/needs%20work",
    "label_color": "ffff00",
    "label_name": "needs work",
    "label_text_color": "ffffff",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/26280#event-359504"
}
```



---

archive/issue_comments_405269.json:
```json
{
    "body": "<div id=\"comment:4\"></div>\n\nBranch pushed to git repo; I updated commit sha1. This was a forced push. New commits:\n<table><tr><td><a href=\"https://github.com/sagemath/sagetrac-mirror/commit/4d7aa64eec851873106dbd14d0944b9bcda8271b\"><code>4d7aa64</code></a></td><td><code>py3: fix this example to ensure it works consistently on python 2 and 3</code></td></tr></table>\n",
    "created_at": "2018-09-17T11:45:52Z",
    "formatter": "markdown",
    "issue": "https://github.com/sagemath/sage/issues/26280",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/26280#issuecomment-405269",
    "user": "https://github.com/sagetrac-git"
}
```

<div id="comment:4"></div>

Branch pushed to git repo; I updated commit sha1. This was a forced push. New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/4d7aa64eec851873106dbd14d0944b9bcda8271b"><code>4d7aa64</code></a></td><td><code>py3: fix this example to ensure it works consistently on python 2 and 3</code></td></tr></table>




---

archive/issue_comments_405270.json:
```json
{
    "body": "Changed commit from **[`33e38b4`](https://github.com/sagemath/sagetrac-mirror/commit/33e38b4c80b32aea35d88624b6483bf61c01127f)** to **[`4d7aa64`](https://github.com/sagemath/sagetrac-mirror/commit/4d7aa64eec851873106dbd14d0944b9bcda8271b)**",
    "created_at": "2018-09-17T11:45:52Z",
    "formatter": "markdown",
    "issue": "https://github.com/sagemath/sage/issues/26280",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/26280#issuecomment-405270",
    "user": "https://github.com/sagetrac-git"
}
```

Changed commit from **[`33e38b4`](https://github.com/sagemath/sagetrac-mirror/commit/33e38b4c80b32aea35d88624b6483bf61c01127f)** to **[`4d7aa64`](https://github.com/sagemath/sagetrac-mirror/commit/4d7aa64eec851873106dbd14d0944b9bcda8271b)**



---

archive/issue_comments_405271.json:
```json
{
    "body": "<div id=\"comment:5\" align=\"right\">comment:5</div>\n\nIt seems Cython on Python 2 has some strange behaviors if you put `isinstance(..., range)`.  So I'm just going to drop that change until we have a better, consistent way to accept arbitrary sequence types in function arguments.",
    "created_at": "2018-09-17T11:47:15Z",
    "formatter": "markdown",
    "issue": "https://github.com/sagemath/sage/issues/26280",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/26280#issuecomment-405271",
    "user": "https://github.com/embray"
}
```

<div id="comment:5" align="right">comment:5</div>

It seems Cython on Python 2 has some strange behaviors if you put `isinstance(..., range)`.  So I'm just going to drop that change until we have a better, consistent way to accept arbitrary sequence types in function arguments.



---

archive/issue_events_359505.json:
```json
{
    "actor": "https://github.com/embray",
    "created_at": "2018-09-17T11:47:22Z",
    "event": "unlabeled",
    "issue": "https://github.com/sagemath/sage/issues/26280",
    "label": "https://github.com/sagemath/sage/labels/needs%20work",
    "label_color": "ffff00",
    "label_name": "needs work",
    "label_text_color": "ffffff",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/26280#event-359505"
}
```



---

archive/issue_events_359506.json:
```json
{
    "actor": "https://github.com/embray",
    "created_at": "2018-09-17T11:47:22Z",
    "event": "labeled",
    "issue": "https://github.com/sagemath/sage/issues/26280",
    "label": "https://github.com/sagemath/sage/labels/positive%20review",
    "label_color": "dfffc0",
    "label_name": "positive review",
    "label_text_color": "ffffff",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/26280#event-359506"
}
```



---

archive/issue_comments_405272.json:
```json
{
    "body": "<div id=\"comment:7\" align=\"right\">comment:7</div>\n\nReplying to [@embray](#comment%3A5):\n> It seems Cython on Python 2 has some strange behaviors if you put `isinstance(..., range)`.  So I'm just going to drop that change until we have a better, consistent way to accept arbitrary sequence types in function arguments.\n\nI would guess that comes from the fact that `range` on Cython is treated as special by the compiler as it can both be treated as `xrange` (e.g., in a `for` loop) and as a list:\n\n```\nsage: %%cython\n....: def test(n):\n....:     return range(n)\nsage: test(5)\n[0, 1, 2, 3, 4]\n```",
    "created_at": "2018-09-17T12:32:50Z",
    "formatter": "markdown",
    "issue": "https://github.com/sagemath/sage/issues/26280",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/26280#issuecomment-405272",
    "user": "https://github.com/tscrim"
}
```

<div id="comment:7" align="right">comment:7</div>

Replying to [@embray](#comment%3A5):
> It seems Cython on Python 2 has some strange behaviors if you put `isinstance(..., range)`.  So I'm just going to drop that change until we have a better, consistent way to accept arbitrary sequence types in function arguments.

I would guess that comes from the fact that `range` on Cython is treated as special by the compiler as it can both be treated as `xrange` (e.g., in a `for` loop) and as a list:

```
sage: %%cython
....: def test(n):
....:     return range(n)
sage: test(5)
[0, 1, 2, 3, 4]
```



---

archive/issue_comments_405273.json:
```json
{
    "body": "<div id=\"comment:8\" align=\"right\">comment:8</div>\n\nWell, yes, but I'm not sure how it translates a statement like `isinstance(..., range)` and I didn't bother to look, but it seems to get up to some funny business for sure.",
    "created_at": "2018-09-17T12:39:08Z",
    "formatter": "markdown",
    "issue": "https://github.com/sagemath/sage/issues/26280",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/26280#issuecomment-405273",
    "user": "https://github.com/embray"
}
```

<div id="comment:8" align="right">comment:8</div>

Well, yes, but I'm not sure how it translates a statement like `isinstance(..., range)` and I didn't bother to look, but it seems to get up to some funny business for sure.



---

archive/issue_events_359507.json:
```json
{
    "actor": "https://github.com/vbraun",
    "created_at": "2018-09-19T07:52:39Z",
    "event": "unlabeled",
    "issue": "https://github.com/sagemath/sage/issues/26280",
    "label": "https://github.com/sagemath/sage/labels/positive%20review",
    "label_color": "dfffc0",
    "label_name": "positive review",
    "label_text_color": "ffffff",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/26280#event-359507"
}
```



---

archive/issue_events_359508.json:
```json
{
    "actor": "https://github.com/vbraun",
    "commit_id": "413d3ec9978843d29251783792f20fcd10221074",
    "commit_repository": "https://github.com/sagemath/sage",
    "created_at": "2018-09-19T07:52:39Z",
    "event": "closed",
    "issue": "https://github.com/sagemath/sage/issues/26280",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/26280#event-359508"
}
```



---

archive/issue_comments_405274.json:
```json
{
    "body": "Changed branch from **[u/embray/python3/sage-rings-polynomial-polydict/misc](https://github.com/sagemath/sagetrac-mirror/tree/u/embray/python3/sage-rings-polynomial-polydict/misc)** to **[`4d7aa64`](https://github.com/sagemath/sagetrac-mirror/commit/4d7aa64eec851873106dbd14d0944b9bcda8271b)**",
    "created_at": "2018-09-19T07:52:39Z",
    "formatter": "markdown",
    "issue": "https://github.com/sagemath/sage/issues/26280",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/26280#issuecomment-405274",
    "user": "https://github.com/vbraun"
}
```

Changed branch from **[u/embray/python3/sage-rings-polynomial-polydict/misc](https://github.com/sagemath/sagetrac-mirror/tree/u/embray/python3/sage-rings-polynomial-polydict/misc)** to **[`4d7aa64`](https://github.com/sagemath/sagetrac-mirror/commit/4d7aa64eec851873106dbd14d0944b9bcda8271b)**
