# Issue 26881: py3: make doctest pass in repl module

archive/issues_026644.json:
```json
{
    "assignees": [],
    "body": "<div id=\"comment:0\"></div>\n\nFix the failling doctests in the sage.repl module :\n\n\n```\nsage -t --long src/sage/repl/configuration.py  # 2 doctests failed\nsage -t --long src/sage/repl/ipython_tests.py  # 5 doctests failed\nsage -t --long src/sage/repl/interpreter.py  # 1 doctest failed\nsage -t --long src/sage/repl/ipython_kernel/widgets_sagenb.py  # 2 doctests failed\nsage -t --long src/sage/repl/ipython_kernel/interact.py  # 1 doctest failed\n```\n\n\n\nComponent: **python3**\n\nAuthor: **Vincent Klein**\n\nBranch: **[`13b9f22`](https://github.com/sagemath/sagetrac-mirror/commit/13b9f224e8b2860a7e15289331e010f06f4387cf)**\n\nReviewer: **Fr\u00e9d\u00e9ric Chapoton**\n\n_Issue created by migration from https://trac.sagemath.org/ticket/26881_\n\n",
    "closed_at": "2019-02-23T23:14:48Z",
    "created_at": "2018-12-12T10:54:15Z",
    "labels": [
        "https://github.com/sagemath/sage/labels/c%3A%20python3",
        "https://github.com/sagemath/sage/labels/p%3A%20major%20/%203",
        "https://github.com/sagemath/sage/labels/enhancement"
    ],
    "milestone": "https://github.com/sagemath/sage/milestones/sage-8.7",
    "reactions": [],
    "repository": "https://github.com/sagemath/sage",
    "title": "py3: make doctest pass in repl module",
    "type": "issue",
    "updated_at": "2019-02-25T15:25:59Z",
    "url": "https://github.com/sagemath/sage/issues/26881",
    "user": "https://github.com/vinklein"
}
```
<div id="comment:0"></div>

Fix the failling doctests in the sage.repl module :


```
sage -t --long src/sage/repl/configuration.py  # 2 doctests failed
sage -t --long src/sage/repl/ipython_tests.py  # 5 doctests failed
sage -t --long src/sage/repl/interpreter.py  # 1 doctest failed
sage -t --long src/sage/repl/ipython_kernel/widgets_sagenb.py  # 2 doctests failed
sage -t --long src/sage/repl/ipython_kernel/interact.py  # 1 doctest failed
```



Component: **python3**

Author: **Vincent Klein**

Branch: **[`13b9f22`](https://github.com/sagemath/sagetrac-mirror/commit/13b9f224e8b2860a7e15289331e010f06f4387cf)**

Reviewer: **Frédéric Chapoton**

_Issue created by migration from https://trac.sagemath.org/ticket/26881_





---

archive/issue_events_366563.json:
```json
{
    "actor": "https://github.com/vinklein",
    "created_at": "2018-12-12T10:54:15Z",
    "event": "milestoned",
    "issue": "https://github.com/sagemath/sage/issues/26881",
    "milestone_number": null,
    "milestone_title": "sage-8.5",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/26881#event-366563"
}
```



---

archive/issue_events_366564.json:
```json
{
    "actor": "https://github.com/vinklein",
    "created_at": "2018-12-12T10:54:15Z",
    "event": "labeled",
    "issue": "https://github.com/sagemath/sage/issues/26881",
    "label": "https://github.com/sagemath/sage/labels/c%3A%20python3",
    "label_color": "0000b0",
    "label_name": "c: python3",
    "label_text_color": "ffffff",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/26881#event-366564"
}
```



---

archive/issue_events_366565.json:
```json
{
    "actor": "https://github.com/vinklein",
    "created_at": "2018-12-12T10:54:15Z",
    "event": "labeled",
    "issue": "https://github.com/sagemath/sage/issues/26881",
    "label": "https://github.com/sagemath/sage/labels/p%3A%20major%20/%203",
    "label_color": "ffbb00",
    "label_name": "p: major / 3",
    "label_text_color": "ffffff",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/26881#event-366565"
}
```



---

archive/issue_events_366566.json:
```json
{
    "actor": "https://github.com/vinklein",
    "created_at": "2018-12-12T10:54:15Z",
    "event": "labeled",
    "issue": "https://github.com/sagemath/sage/issues/26881",
    "label": "https://github.com/sagemath/sage/labels/enhancement",
    "label_color": "696969",
    "label_name": "enhancement",
    "label_text_color": "ffffff",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/26881#event-366566"
}
```



---

archive/issue_events_366567.json:
```json
{
    "actor": "https://github.com/fchapoton",
    "created_at": "2018-12-29T14:37:48Z",
    "event": "demilestoned",
    "issue": "https://github.com/sagemath/sage/issues/26881",
    "milestone_number": null,
    "milestone_title": "sage-8.5",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/26881#event-366567"
}
```



---

archive/issue_events_366568.json:
```json
{
    "actor": "https://github.com/fchapoton",
    "created_at": "2018-12-29T14:37:48Z",
    "event": "milestoned",
    "issue": "https://github.com/sagemath/sage/issues/26881",
    "milestone_number": null,
    "milestone_title": "sage-8.7",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/26881#event-366568"
}
```



---

archive/issue_comments_413893.json:
```json
{
    "body": "Branch: **[u/vklein/26881](https://github.com/sagemath/sagetrac-mirror/tree/u/vklein/26881)**",
    "created_at": "2019-02-22T14:39:06Z",
    "formatter": "markdown",
    "issue": "https://github.com/sagemath/sage/issues/26881",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/26881#issuecomment-413893",
    "user": "https://github.com/vinklein"
}
```

Branch: **[u/vklein/26881](https://github.com/sagemath/sagetrac-mirror/tree/u/vklein/26881)**



---

archive/issue_events_366569.json:
```json
{
    "actor": "https://github.com/vinklein",
    "created_at": "2019-02-22T14:46:07Z",
    "event": "labeled",
    "issue": "https://github.com/sagemath/sage/issues/26881",
    "label": "https://github.com/sagemath/sage/labels/needs%20review",
    "label_color": "7fff00",
    "label_name": "needs review",
    "label_text_color": "ffffff",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/26881#event-366569"
}
```



---

archive/issue_comments_413894.json:
```json
{
    "body": "Commit: **[`13b9f22`](https://github.com/sagemath/sagetrac-mirror/commit/13b9f224e8b2860a7e15289331e010f06f4387cf)**",
    "created_at": "2019-02-22T14:46:07Z",
    "formatter": "markdown",
    "issue": "https://github.com/sagemath/sage/issues/26881",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/26881#issuecomment-413894",
    "user": "https://github.com/vinklein"
}
```

Commit: **[`13b9f22`](https://github.com/sagemath/sagetrac-mirror/commit/13b9f224e8b2860a7e15289331e010f06f4387cf)**



---

archive/issue_comments_413895.json:
```json
{
    "body": "Description changed:\n``````diff\n--- \n+++ \n@@ -1 +1,8 @@\n+Fix the failling doctests in the sage.repl module :\n \n+sage -t --long src/sage/repl/configuration.py  # 2 doctests failed\n+sage -t --long src/sage/repl/ipython_tests.py  # 5 doctests failed\n+sage -t --long src/sage/repl/interpreter.py  # 1 doctest failed\n+sage -t --long src/sage/repl/ipython_kernel/widgets_sagenb.py  # 2 doctests failed\n+sage -t --long src/sage/repl/ipython_kernel/interact.py  # 1 doctest failed\n+\n``````\n",
    "created_at": "2019-02-22T14:46:07Z",
    "formatter": "markdown",
    "issue": "https://github.com/sagemath/sage/issues/26881",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/26881#issuecomment-413895",
    "user": "https://github.com/vinklein"
}
```

Description changed:
``````diff
--- 
+++ 
@@ -1 +1,8 @@
+Fix the failling doctests in the sage.repl module :
 
+sage -t --long src/sage/repl/configuration.py  # 2 doctests failed
+sage -t --long src/sage/repl/ipython_tests.py  # 5 doctests failed
+sage -t --long src/sage/repl/interpreter.py  # 1 doctest failed
+sage -t --long src/sage/repl/ipython_kernel/widgets_sagenb.py  # 2 doctests failed
+sage -t --long src/sage/repl/ipython_kernel/interact.py  # 1 doctest failed
+
``````




---

archive/issue_comments_413896.json:
```json
{
    "body": "<div id=\"comment:3\"></div>\n\nNew commits:\n<table><tr><td><a href=\"https://github.com/sagemath/sagetrac-mirror/commit/13b9f224e8b2860a7e15289331e010f06f4387cf\"><code>13b9f22</code></a></td><td><code>Trac #26881: py3 Fix repl module for python3</code></td></tr></table>\n",
    "created_at": "2019-02-22T14:46:07Z",
    "formatter": "markdown",
    "issue": "https://github.com/sagemath/sage/issues/26881",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/26881#issuecomment-413896",
    "user": "https://github.com/vinklein"
}
```

<div id="comment:3"></div>

New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/13b9f224e8b2860a7e15289331e010f06f4387cf"><code>13b9f22</code></a></td><td><code>Trac #26881: py3 Fix repl module for python3</code></td></tr></table>




---

archive/issue_comments_413897.json:
```json
{
    "body": "Description changed:\n``````diff\n--- \n+++ \n@@ -1,8 +1,16 @@\n Fix the failling doctests in the sage.repl module :\n \n sage -t --long src/sage/repl/configuration.py  # 2 doctests failed\n+\n+\n sage -t --long src/sage/repl/ipython_tests.py  # 5 doctests failed\n+\n+\n sage -t --long src/sage/repl/interpreter.py  # 1 doctest failed\n+\n+\n sage -t --long src/sage/repl/ipython_kernel/widgets_sagenb.py  # 2 doctests failed\n+\n+\n sage -t --long src/sage/repl/ipython_kernel/interact.py  # 1 doctest failed\n \n``````\n",
    "created_at": "2019-02-22T14:55:08Z",
    "formatter": "markdown",
    "issue": "https://github.com/sagemath/sage/issues/26881",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/26881#issuecomment-413897",
    "user": "https://github.com/vinklein"
}
```

Description changed:
``````diff
--- 
+++ 
@@ -1,8 +1,16 @@
 Fix the failling doctests in the sage.repl module :
 
 sage -t --long src/sage/repl/configuration.py  # 2 doctests failed
+
+
 sage -t --long src/sage/repl/ipython_tests.py  # 5 doctests failed
+
+
 sage -t --long src/sage/repl/interpreter.py  # 1 doctest failed
+
+
 sage -t --long src/sage/repl/ipython_kernel/widgets_sagenb.py  # 2 doctests failed
+
+
 sage -t --long src/sage/repl/ipython_kernel/interact.py  # 1 doctest failed
 
``````




---

archive/issue_comments_413898.json:
```json
{
    "body": "Description changed:\n``````diff\n--- \n+++ \n@@ -1,16 +1,12 @@\n Fix the failling doctests in the sage.repl module :\n \n+\n+```\n sage -t --long src/sage/repl/configuration.py  # 2 doctests failed\n+sage -t --long src/sage/repl/ipython_tests.py  # 5 doctests failed\n+sage -t --long src/sage/repl/interpreter.py  # 1 doctest failed\n+sage -t --long src/sage/repl/ipython_kernel/widgets_sagenb.py  # 2 doctests failed\n+sage -t --long src/sage/repl/ipython_kernel/interact.py  # 1 doctest failed\n+```\n \n \n-sage -t --long src/sage/repl/ipython_tests.py  # 5 doctests failed\n-\n-\n-sage -t --long src/sage/repl/interpreter.py  # 1 doctest failed\n-\n-\n-sage -t --long src/sage/repl/ipython_kernel/widgets_sagenb.py  # 2 doctests failed\n-\n-\n-sage -t --long src/sage/repl/ipython_kernel/interact.py  # 1 doctest failed\n-\n``````\n",
    "created_at": "2019-02-22T14:55:48Z",
    "formatter": "markdown",
    "issue": "https://github.com/sagemath/sage/issues/26881",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/26881#issuecomment-413898",
    "user": "https://github.com/vinklein"
}
```

Description changed:
``````diff
--- 
+++ 
@@ -1,16 +1,12 @@
 Fix the failling doctests in the sage.repl module :
 
+
+```
 sage -t --long src/sage/repl/configuration.py  # 2 doctests failed
+sage -t --long src/sage/repl/ipython_tests.py  # 5 doctests failed
+sage -t --long src/sage/repl/interpreter.py  # 1 doctest failed
+sage -t --long src/sage/repl/ipython_kernel/widgets_sagenb.py  # 2 doctests failed
+sage -t --long src/sage/repl/ipython_kernel/interact.py  # 1 doctest failed
+```
 
 
-sage -t --long src/sage/repl/ipython_tests.py  # 5 doctests failed
-
-
-sage -t --long src/sage/repl/interpreter.py  # 1 doctest failed
-
-
-sage -t --long src/sage/repl/ipython_kernel/widgets_sagenb.py  # 2 doctests failed
-
-
-sage -t --long src/sage/repl/ipython_kernel/interact.py  # 1 doctest failed
-
``````




---

archive/issue_comments_413899.json:
```json
{
    "body": "<div id=\"comment:6\" align=\"right\">comment:6</div>\n\nWell, I find it suspect that OrderedDict does not display in the given order in py2..\n\nBut let us keep that for another ticket..",
    "created_at": "2019-02-22T19:28:28Z",
    "formatter": "markdown",
    "issue": "https://github.com/sagemath/sage/issues/26881",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/26881#issuecomment-413899",
    "user": "https://github.com/fchapoton"
}
```

<div id="comment:6" align="right">comment:6</div>

Well, I find it suspect that OrderedDict does not display in the given order in py2..

But let us keep that for another ticket..



---

archive/issue_comments_413900.json:
```json
{
    "body": "Reviewer: **Fr\u00e9d\u00e9ric Chapoton**",
    "created_at": "2019-02-22T19:28:28Z",
    "formatter": "markdown",
    "issue": "https://github.com/sagemath/sage/issues/26881",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/26881#issuecomment-413900",
    "user": "https://github.com/fchapoton"
}
```

Reviewer: **Frédéric Chapoton**



---

archive/issue_events_366570.json:
```json
{
    "actor": "https://github.com/fchapoton",
    "created_at": "2019-02-22T19:28:28Z",
    "event": "unlabeled",
    "issue": "https://github.com/sagemath/sage/issues/26881",
    "label": "https://github.com/sagemath/sage/labels/needs%20review",
    "label_color": "7fff00",
    "label_name": "needs review",
    "label_text_color": "ffffff",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/26881#event-366570"
}
```



---

archive/issue_events_366571.json:
```json
{
    "actor": "https://github.com/fchapoton",
    "created_at": "2019-02-22T19:28:28Z",
    "event": "labeled",
    "issue": "https://github.com/sagemath/sage/issues/26881",
    "label": "https://github.com/sagemath/sage/labels/positive%20review",
    "label_color": "dfffc0",
    "label_name": "positive review",
    "label_text_color": "ffffff",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/26881#event-366571"
}
```



---

archive/issue_comments_413901.json:
```json
{
    "body": "Changed branch from **[u/vklein/26881](https://github.com/sagemath/sagetrac-mirror/tree/u/vklein/26881)** to **[`13b9f22`](https://github.com/sagemath/sagetrac-mirror/commit/13b9f224e8b2860a7e15289331e010f06f4387cf)**",
    "created_at": "2019-02-23T23:14:48Z",
    "formatter": "markdown",
    "issue": "https://github.com/sagemath/sage/issues/26881",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/26881#issuecomment-413901",
    "user": "https://github.com/vbraun"
}
```

Changed branch from **[u/vklein/26881](https://github.com/sagemath/sagetrac-mirror/tree/u/vklein/26881)** to **[`13b9f22`](https://github.com/sagemath/sagetrac-mirror/commit/13b9f224e8b2860a7e15289331e010f06f4387cf)**



---

archive/issue_events_366572.json:
```json
{
    "actor": "https://github.com/vbraun",
    "created_at": "2019-02-23T23:14:48Z",
    "event": "unlabeled",
    "issue": "https://github.com/sagemath/sage/issues/26881",
    "label": "https://github.com/sagemath/sage/labels/positive%20review",
    "label_color": "dfffc0",
    "label_name": "positive review",
    "label_text_color": "ffffff",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/26881#event-366572"
}
```



---

archive/issue_events_366573.json:
```json
{
    "actor": "https://github.com/vbraun",
    "commit_id": "3bdf67f91405e1a42711b3aad2291e0746223269",
    "commit_repository": "https://github.com/sagemath/sage",
    "created_at": "2019-02-23T23:14:48Z",
    "event": "closed",
    "issue": "https://github.com/sagemath/sage/issues/26881",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/26881#event-366573"
}
```



---

archive/issue_comments_413902.json:
```json
{
    "body": "<div id=\"comment:8\" align=\"right\">comment:8</div>\n\nI still get\n\n```\nsage -t --long src/sage/repl/attach.py  # 4 doctests failed\n```\nnamely\n\n```\nsage -t --long src/sage/repl/attach.py\n**********************************************************************\nFile \"src/sage/repl/attach.py\", line 36, in sage.repl.attach\nFailed example:\n    try:\n        attach(src)\n    except Exception:\n        traceback.print_exc()\nExpected:\n    Traceback (most recent call last):\n    ...\n        exec(preparse_file(f.read()) + \"\\n\", globals)\n      File \"<string>\", line 3, in <module>\n    ValueError: third\nGot:\n    <BLANKLINE>\n**********************************************************************\nFile \"src/sage/repl/attach.py\", line 45, in sage.repl.attach\nFailed example:\n    detach(src)\nExpected nothing\nGot:\n    Traceback (most recent call last):\n      File \"<doctest sage.repl.attach[10]>\", line 2, in <module>\n        attach(src)\n      File \"sage/misc/lazy_import.pyx\", line 354, in sage.misc.lazy_import.LazyImport.__call__ (build/cythonized/sage/misc/lazy_import.c:3683)\n        return self.get_object()(*args, **kwds)\n      File \"/home/u1/chapoton/sage3/local/lib/python3.6/site-packages/sage/repl/attach.py\", line 356, in attach\n        load(filename, globals(), attach=True)\n      File \"/home/u1/chapoton/sage3/local/lib/python3.6/site-packages/sage/repl/load.py\", line 272, in load\n        exec(preparse_file(f.read()) + \"\\n\", globals)\n      File \"<string>\", line 3, in <module>\n    ValueError: third\n**********************************************************************\nFile \"src/sage/repl/attach.py\", line 48, in sage.repl.attach\nFailed example:\n    try:\n        attach(src)\n    except Exception:\n        traceback.print_exc()\nExpected:\n    Traceback (most recent call last):\n    ...\n        exec(code, globals)\n      File \".../foobar.sage....py\", line ..., in <module>\n        raise ValueError(\"third\")   # this should appear in the source snippet\n    ValueError: third\nGot:\n    <BLANKLINE>\n**********************************************************************\nFile \"src/sage/repl/attach.py\", line 58, in sage.repl.attach\nFailed example:\n    detach(src)\nExpected nothing\nGot:\n    Traceback (most recent call last):\n      File \"<doctest sage.repl.attach[13]>\", line 2, in <module>\n        attach(src)\n      File \"sage/misc/lazy_import.pyx\", line 354, in sage.misc.lazy_import.LazyImport.__call__ (build/cythonized/sage/misc/lazy_import.c:3683)\n        return self.get_object()(*args, **kwds)\n      File \"/home/u1/chapoton/sage3/local/lib/python3.6/site-packages/sage/repl/attach.py\", line 356, in attach\n        load(filename, globals(), attach=True)\n      File \"/home/u1/chapoton/sage3/local/lib/python3.6/site-packages/sage/repl/load.py\", line 266, in load\n        exec(code, globals)\n      File \"/home/u1/chapoton/.sage/temp/atlas/6848/foobar.sage8jw3wb2i.py\", line 7, in <module>\n        raise ValueError(\"third\")   # this should appear in the source snippet\n    ValueError: third\n```",
    "created_at": "2019-02-25T14:43:41Z",
    "formatter": "markdown",
    "issue": "https://github.com/sagemath/sage/issues/26881",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/26881#issuecomment-413902",
    "user": "https://github.com/fchapoton"
}
```

<div id="comment:8" align="right">comment:8</div>

I still get

```
sage -t --long src/sage/repl/attach.py  # 4 doctests failed
```
namely

```
sage -t --long src/sage/repl/attach.py
**********************************************************************
File "src/sage/repl/attach.py", line 36, in sage.repl.attach
Failed example:
    try:
        attach(src)
    except Exception:
        traceback.print_exc()
Expected:
    Traceback (most recent call last):
    ...
        exec(preparse_file(f.read()) + "\n", globals)
      File "<string>", line 3, in <module>
    ValueError: third
Got:
    <BLANKLINE>
**********************************************************************
File "src/sage/repl/attach.py", line 45, in sage.repl.attach
Failed example:
    detach(src)
Expected nothing
Got:
    Traceback (most recent call last):
      File "<doctest sage.repl.attach[10]>", line 2, in <module>
        attach(src)
      File "sage/misc/lazy_import.pyx", line 354, in sage.misc.lazy_import.LazyImport.__call__ (build/cythonized/sage/misc/lazy_import.c:3683)
        return self.get_object()(*args, **kwds)
      File "/home/u1/chapoton/sage3/local/lib/python3.6/site-packages/sage/repl/attach.py", line 356, in attach
        load(filename, globals(), attach=True)
      File "/home/u1/chapoton/sage3/local/lib/python3.6/site-packages/sage/repl/load.py", line 272, in load
        exec(preparse_file(f.read()) + "\n", globals)
      File "<string>", line 3, in <module>
    ValueError: third
**********************************************************************
File "src/sage/repl/attach.py", line 48, in sage.repl.attach
Failed example:
    try:
        attach(src)
    except Exception:
        traceback.print_exc()
Expected:
    Traceback (most recent call last):
    ...
        exec(code, globals)
      File ".../foobar.sage....py", line ..., in <module>
        raise ValueError("third")   # this should appear in the source snippet
    ValueError: third
Got:
    <BLANKLINE>
**********************************************************************
File "src/sage/repl/attach.py", line 58, in sage.repl.attach
Failed example:
    detach(src)
Expected nothing
Got:
    Traceback (most recent call last):
      File "<doctest sage.repl.attach[13]>", line 2, in <module>
        attach(src)
      File "sage/misc/lazy_import.pyx", line 354, in sage.misc.lazy_import.LazyImport.__call__ (build/cythonized/sage/misc/lazy_import.c:3683)
        return self.get_object()(*args, **kwds)
      File "/home/u1/chapoton/sage3/local/lib/python3.6/site-packages/sage/repl/attach.py", line 356, in attach
        load(filename, globals(), attach=True)
      File "/home/u1/chapoton/sage3/local/lib/python3.6/site-packages/sage/repl/load.py", line 266, in load
        exec(code, globals)
      File "/home/u1/chapoton/.sage/temp/atlas/6848/foobar.sage8jw3wb2i.py", line 7, in <module>
        raise ValueError("third")   # this should appear in the source snippet
    ValueError: third
```



---

archive/issue_comments_413903.json:
```json
{
    "body": "Changed commit from **[`13b9f22`](https://github.com/sagemath/sagetrac-mirror/commit/13b9f224e8b2860a7e15289331e010f06f4387cf)** to none",
    "created_at": "2019-02-25T14:43:41Z",
    "formatter": "markdown",
    "issue": "https://github.com/sagemath/sage/issues/26881",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/26881#issuecomment-413903",
    "user": "https://github.com/fchapoton"
}
```

Changed commit from **[`13b9f22`](https://github.com/sagemath/sagetrac-mirror/commit/13b9f224e8b2860a7e15289331e010f06f4387cf)** to none



---

archive/issue_comments_413904.json:
```json
{
    "body": "<div id=\"comment:9\" align=\"right\">comment:9</div>\n\nI don't get that `attach.py` tests pass (as the whole module) in `py2` and `py3` on my computers. Do you use optional modules ?",
    "created_at": "2019-02-25T15:22:31Z",
    "formatter": "markdown",
    "issue": "https://github.com/sagemath/sage/issues/26881",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/26881#issuecomment-413904",
    "user": "https://github.com/vinklein"
}
```

<div id="comment:9" align="right">comment:9</div>

I don't get that `attach.py` tests pass (as the whole module) in `py2` and `py3` on my computers. Do you use optional modules ?



---

archive/issue_comments_413905.json:
```json
{
    "body": "<div id=\"comment:10\" align=\"right\">comment:10</div>\n\nindeed, the tests pass when run alone on the patchbot machine and another machine. So they only fail in the patchbot run.\n\nNote that the failures seems to be a shift in the answers: each doctests receives the output of the previous doctest..",
    "created_at": "2019-02-25T15:25:59Z",
    "formatter": "markdown",
    "issue": "https://github.com/sagemath/sage/issues/26881",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/26881#issuecomment-413905",
    "user": "https://github.com/fchapoton"
}
```

<div id="comment:10" align="right">comment:10</div>

indeed, the tests pass when run alone on the patchbot machine and another machine. So they only fail in the patchbot run.

Note that the failures seems to be a shift in the answers: each doctests receives the output of the previous doctest..
