# Issue 26881: py3: make doctest pass in repl module

archive/issues_026644.json:
```json
{
    "body": "Fix the failling doctests in the sage.repl module :\n\n\n```\nsage -t --long src/sage/repl/configuration.py  # 2 doctests failed\nsage -t --long src/sage/repl/ipython_tests.py  # 5 doctests failed\nsage -t --long src/sage/repl/interpreter.py  # 1 doctest failed\nsage -t --long src/sage/repl/ipython_kernel/widgets_sagenb.py  # 2 doctests failed\nsage -t --long src/sage/repl/ipython_kernel/interact.py  # 1 doctest failed\n```\n\n\n\n**Branch:** [13b9f224e8b2860a7e15289331e010f06f4387cf](https://github.com/sagemath/sagetrac-mirror/commit/13b9f224e8b2860a7e15289331e010f06f4387cf)\n\n**Reviewer:** Fr\u00e9d\u00e9ric Chapoton\n\n**Author:** Vincent Klein\n\nIssue created by migration from https://trac.sagemath.org/ticket/26881\n\n",
    "closed_at": "2019-02-23T23:14:48Z",
    "created_at": "2018-12-12T10:54:15Z",
    "labels": [
        "component: python3",
        "enhancement"
    ],
    "milestone": "https://github.com/sagemath/sage/milestones/sage-8.7",
    "title": "py3: make doctest pass in repl module",
    "type": "issue",
    "url": "https://github.com/sagemath/sage/issues/26881",
    "user": "https://github.com/vinklein"
}
```
Fix the failling doctests in the sage.repl module :


```
sage -t --long src/sage/repl/configuration.py  # 2 doctests failed
sage -t --long src/sage/repl/ipython_tests.py  # 5 doctests failed
sage -t --long src/sage/repl/interpreter.py  # 1 doctest failed
sage -t --long src/sage/repl/ipython_kernel/widgets_sagenb.py  # 2 doctests failed
sage -t --long src/sage/repl/ipython_kernel/interact.py  # 1 doctest failed
```



**Branch:** [13b9f224e8b2860a7e15289331e010f06f4387cf](https://github.com/sagemath/sagetrac-mirror/commit/13b9f224e8b2860a7e15289331e010f06f4387cf)

**Reviewer:** Frédéric Chapoton

**Author:** Vincent Klein

Issue created by migration from https://trac.sagemath.org/ticket/26881





---

archive/issue_events_239378.json:
```json
{
    "actor": "https://github.com/fchapoton",
    "created_at": "2018-12-29T14:37:48Z",
    "event": "demilestoned",
    "issue": "https://github.com/sagemath/sage/issues/26881",
    "milestone": "sage-8.5",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/26881#event-239378"
}
```



---

archive/issue_events_239379.json:
```json
{
    "actor": "https://github.com/fchapoton",
    "created_at": "2018-12-29T14:37:48Z",
    "event": "milestoned",
    "issue": "https://github.com/sagemath/sage/issues/26881",
    "milestone": "sage-8.7",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/26881#event-239379"
}
```



---

archive/issue_comments_416552.json:
```json
{
    "body": "**Branch:** [u/vklein/26881](https://github.com/sagemath/sagetrac-mirror/tree/u/vklein/26881)",
    "created_at": "2019-02-22T14:39:06Z",
    "issue": "https://github.com/sagemath/sage/issues/26881",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/26881#issuecomment-416552",
    "user": "https://github.com/vinklein"
}
```

**Branch:** [u/vklein/26881](https://github.com/sagemath/sagetrac-mirror/tree/u/vklein/26881)



---

archive/issue_events_239380.json:
```json
{
    "actor": "https://github.com/vinklein",
    "created_at": "2019-02-22T14:46:07Z",
    "event": "labeled",
    "issue": "https://github.com/sagemath/sage/issues/26881",
    "label": "needs review",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/26881#event-239380"
}
```



---

archive/issue_comments_416553.json:
```json
{
    "body": "**Commit:** [13b9f224e8b2860a7e15289331e010f06f4387cf](https://github.com/sagemath/sagetrac-mirror/commit/13b9f224e8b2860a7e15289331e010f06f4387cf)",
    "created_at": "2019-02-22T14:46:07Z",
    "issue": "https://github.com/sagemath/sage/issues/26881",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/26881#issuecomment-416553",
    "user": "https://github.com/vinklein"
}
```

**Commit:** [13b9f224e8b2860a7e15289331e010f06f4387cf](https://github.com/sagemath/sagetrac-mirror/commit/13b9f224e8b2860a7e15289331e010f06f4387cf)



---

archive/issue_comments_416554.json:
```json
{
    "body": "**Description changed:**\n``````diff\n--- \n+++ \n@@ -1 +1,8 @@\n+Fix the failling doctests in the sage.repl module :\n \n+sage -t --long src/sage/repl/configuration.py  # 2 doctests failed\n+sage -t --long src/sage/repl/ipython_tests.py  # 5 doctests failed\n+sage -t --long src/sage/repl/interpreter.py  # 1 doctest failed\n+sage -t --long src/sage/repl/ipython_kernel/widgets_sagenb.py  # 2 doctests failed\n+sage -t --long src/sage/repl/ipython_kernel/interact.py  # 1 doctest failed\n+\n``````\n",
    "created_at": "2019-02-22T14:46:07Z",
    "issue": "https://github.com/sagemath/sage/issues/26881",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/26881#issuecomment-416554",
    "user": "https://github.com/vinklein"
}
```

**Description changed:**
``````diff
--- 
+++ 
@@ -1 +1,8 @@
+Fix the failling doctests in the sage.repl module :
 
+sage -t --long src/sage/repl/configuration.py  # 2 doctests failed
+sage -t --long src/sage/repl/ipython_tests.py  # 5 doctests failed
+sage -t --long src/sage/repl/interpreter.py  # 1 doctest failed
+sage -t --long src/sage/repl/ipython_kernel/widgets_sagenb.py  # 2 doctests failed
+sage -t --long src/sage/repl/ipython_kernel/interact.py  # 1 doctest failed
+
``````




---

archive/issue_comments_416555.json:
```json
{
    "body": "<a id='comment:3'></a>\n**New commits:**\n<table><tr><td><a href=\"https://github.com/sagemath/sagetrac-mirror/commit/13b9f224e8b2860a7e15289331e010f06f4387cf\">13b9f22</a></td><td><code>Trac #26881: py3 Fix repl module for python3</code></td></tr></table>\n",
    "created_at": "2019-02-22T14:46:07Z",
    "issue": "https://github.com/sagemath/sage/issues/26881",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/26881#issuecomment-416555",
    "user": "https://github.com/vinklein"
}
```

<a id='comment:3'></a>
**New commits:**
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/13b9f224e8b2860a7e15289331e010f06f4387cf">13b9f22</a></td><td><code>Trac #26881: py3 Fix repl module for python3</code></td></tr></table>




---

archive/issue_comments_416556.json:
```json
{
    "body": "**Description changed:**\n``````diff\n--- \n+++ \n@@ -1,8 +1,12 @@\n Fix the failling doctests in the sage.repl module :\n \n-sage -t --long src/sage/repl/configuration.py  # 2 doctests failed\n-sage -t --long src/sage/repl/ipython_tests.py  # 5 doctests failed\n-sage -t --long src/sage/repl/interpreter.py  # 1 doctest failed\n-sage -t --long src/sage/repl/ipython_kernel/widgets_sagenb.py  # 2 doctests failed\n+sage -t --long src/sage/repl/configuration.py  # 2 doctests failed\\\\\n+\n+sage -t --long src/sage/repl/ipython_tests.py  # 5 doctests failed\\\\\n+\n+sage -t --long src/sage/repl/interpreter.py  # 1 doctest failed\\\\\n+\n+sage -t --long src/sage/repl/ipython_kernel/widgets_sagenb.py  # 2 doctests failed\\\\\n+\n sage -t --long src/sage/repl/ipython_kernel/interact.py  # 1 doctest failed\n \n``````\n",
    "created_at": "2019-02-22T14:55:08Z",
    "issue": "https://github.com/sagemath/sage/issues/26881",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/26881#issuecomment-416556",
    "user": "https://github.com/vinklein"
}
```

**Description changed:**
``````diff
--- 
+++ 
@@ -1,8 +1,12 @@
 Fix the failling doctests in the sage.repl module :
 
-sage -t --long src/sage/repl/configuration.py  # 2 doctests failed
-sage -t --long src/sage/repl/ipython_tests.py  # 5 doctests failed
-sage -t --long src/sage/repl/interpreter.py  # 1 doctest failed
-sage -t --long src/sage/repl/ipython_kernel/widgets_sagenb.py  # 2 doctests failed
+sage -t --long src/sage/repl/configuration.py  # 2 doctests failed\\
+
+sage -t --long src/sage/repl/ipython_tests.py  # 5 doctests failed\\
+
+sage -t --long src/sage/repl/interpreter.py  # 1 doctest failed\\
+
+sage -t --long src/sage/repl/ipython_kernel/widgets_sagenb.py  # 2 doctests failed\\
+
 sage -t --long src/sage/repl/ipython_kernel/interact.py  # 1 doctest failed
 
``````




---

archive/issue_comments_416557.json:
```json
{
    "body": "**Description changed:**\n``````diff\n--- \n+++ \n@@ -1,12 +1,12 @@\n Fix the failling doctests in the sage.repl module :\n \n-sage -t --long src/sage/repl/configuration.py  # 2 doctests failed\\\\\n \n-sage -t --long src/sage/repl/ipython_tests.py  # 5 doctests failed\\\\\n+```\n+sage -t --long src/sage/repl/configuration.py  # 2 doctests failed\n+sage -t --long src/sage/repl/ipython_tests.py  # 5 doctests failed\n+sage -t --long src/sage/repl/interpreter.py  # 1 doctest failed\n+sage -t --long src/sage/repl/ipython_kernel/widgets_sagenb.py  # 2 doctests failed\n+sage -t --long src/sage/repl/ipython_kernel/interact.py  # 1 doctest failed\n+```\n \n-sage -t --long src/sage/repl/interpreter.py  # 1 doctest failed\\\\\n \n-sage -t --long src/sage/repl/ipython_kernel/widgets_sagenb.py  # 2 doctests failed\\\\\n-\n-sage -t --long src/sage/repl/ipython_kernel/interact.py  # 1 doctest failed\n-\n``````\n",
    "created_at": "2019-02-22T14:55:48Z",
    "issue": "https://github.com/sagemath/sage/issues/26881",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/26881#issuecomment-416557",
    "user": "https://github.com/vinklein"
}
```

**Description changed:**
``````diff
--- 
+++ 
@@ -1,12 +1,12 @@
 Fix the failling doctests in the sage.repl module :
 
-sage -t --long src/sage/repl/configuration.py  # 2 doctests failed\\
 
-sage -t --long src/sage/repl/ipython_tests.py  # 5 doctests failed\\
+```
+sage -t --long src/sage/repl/configuration.py  # 2 doctests failed
+sage -t --long src/sage/repl/ipython_tests.py  # 5 doctests failed
+sage -t --long src/sage/repl/interpreter.py  # 1 doctest failed
+sage -t --long src/sage/repl/ipython_kernel/widgets_sagenb.py  # 2 doctests failed
+sage -t --long src/sage/repl/ipython_kernel/interact.py  # 1 doctest failed
+```
 
-sage -t --long src/sage/repl/interpreter.py  # 1 doctest failed\\
 
-sage -t --long src/sage/repl/ipython_kernel/widgets_sagenb.py  # 2 doctests failed\\
-
-sage -t --long src/sage/repl/ipython_kernel/interact.py  # 1 doctest failed
-
``````




---

archive/issue_comments_416558.json:
```json
{
    "body": "<a id='comment:6'></a>\nWell, I find it suspect that OrderedDict does not display in the given order in py2..\n\nBut let us keep that for another ticket..",
    "created_at": "2019-02-22T19:28:28Z",
    "issue": "https://github.com/sagemath/sage/issues/26881",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/26881#issuecomment-416558",
    "user": "https://github.com/fchapoton"
}
```

<a id='comment:6'></a>
Well, I find it suspect that OrderedDict does not display in the given order in py2..

But let us keep that for another ticket..



---

archive/issue_comments_416559.json:
```json
{
    "body": "**Reviewer:** Fr\u00e9d\u00e9ric Chapoton",
    "created_at": "2019-02-22T19:28:28Z",
    "issue": "https://github.com/sagemath/sage/issues/26881",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/26881#issuecomment-416559",
    "user": "https://github.com/fchapoton"
}
```

**Reviewer:** Frédéric Chapoton



---

archive/issue_events_239381.json:
```json
{
    "actor": "https://github.com/fchapoton",
    "created_at": "2019-02-22T19:28:28Z",
    "event": "unlabeled",
    "issue": "https://github.com/sagemath/sage/issues/26881",
    "label": "needs review",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/26881#event-239381"
}
```



---

archive/issue_events_239382.json:
```json
{
    "actor": "https://github.com/fchapoton",
    "created_at": "2019-02-22T19:28:28Z",
    "event": "labeled",
    "issue": "https://github.com/sagemath/sage/issues/26881",
    "label": "positive review",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/26881#event-239382"
}
```



---

archive/issue_comments_416560.json:
```json
{
    "body": "**Changing branch** from \"[u/vklein/26881](https://github.com/sagemath/sagetrac-mirror/tree/u/vklein/26881)\" to \"[13b9f224e8b2860a7e15289331e010f06f4387cf](https://github.com/sagemath/sagetrac-mirror/commit/13b9f224e8b2860a7e15289331e010f06f4387cf)\".",
    "created_at": "2019-02-23T23:14:48Z",
    "issue": "https://github.com/sagemath/sage/issues/26881",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/26881#issuecomment-416560",
    "user": "https://github.com/vbraun"
}
```

**Changing branch** from "[u/vklein/26881](https://github.com/sagemath/sagetrac-mirror/tree/u/vklein/26881)" to "[13b9f224e8b2860a7e15289331e010f06f4387cf](https://github.com/sagemath/sagetrac-mirror/commit/13b9f224e8b2860a7e15289331e010f06f4387cf)".



---

archive/issue_events_239383.json:
```json
{
    "actor": "https://github.com/vbraun",
    "created_at": "2019-02-23T23:14:48Z",
    "event": "unlabeled",
    "issue": "https://github.com/sagemath/sage/issues/26881",
    "label": "positive review",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/26881#event-239383"
}
```



---

archive/issue_events_239384.json:
```json
{
    "actor": "https://github.com/vbraun",
    "commit_id": "3bdf67f91405e1a42711b3aad2291e0746223269",
    "created_at": "2019-02-23T23:14:48Z",
    "event": "closed",
    "issue": "https://github.com/sagemath/sage/issues/26881",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/26881#event-239384"
}
```



---

archive/issue_comments_416561.json:
```json
{
    "body": "<a id='comment:8'></a>\nI still get\n\n```\nsage -t --long src/sage/repl/attach.py  # 4 doctests failed\n```\nnamely\n\n```\nsage -t --long src/sage/repl/attach.py\n**********************************************************************\nFile \"src/sage/repl/attach.py\", line 36, in sage.repl.attach\nFailed example:\n    try:\n        attach(src)\n    except Exception:\n        traceback.print_exc()\nExpected:\n    Traceback (most recent call last):\n    ...\n        exec(preparse_file(f.read()) + \"\\n\", globals)\n      File \"<string>\", line 3, in <module>\n    ValueError: third\nGot:\n    <BLANKLINE>\n**********************************************************************\nFile \"src/sage/repl/attach.py\", line 45, in sage.repl.attach\nFailed example:\n    detach(src)\nExpected nothing\nGot:\n    Traceback (most recent call last):\n      File \"<doctest sage.repl.attach[10]>\", line 2, in <module>\n        attach(src)\n      File \"sage/misc/lazy_import.pyx\", line 354, in sage.misc.lazy_import.LazyImport.__call__ (build/cythonized/sage/misc/lazy_import.c:3683)\n        return self.get_object()(*args, **kwds)\n      File \"/home/u1/chapoton/sage3/local/lib/python3.6/site-packages/sage/repl/attach.py\", line 356, in attach\n        load(filename, globals(), attach=True)\n      File \"/home/u1/chapoton/sage3/local/lib/python3.6/site-packages/sage/repl/load.py\", line 272, in load\n        exec(preparse_file(f.read()) + \"\\n\", globals)\n      File \"<string>\", line 3, in <module>\n    ValueError: third\n**********************************************************************\nFile \"src/sage/repl/attach.py\", line 48, in sage.repl.attach\nFailed example:\n    try:\n        attach(src)\n    except Exception:\n        traceback.print_exc()\nExpected:\n    Traceback (most recent call last):\n    ...\n        exec(code, globals)\n      File \".../foobar.sage....py\", line ..., in <module>\n        raise ValueError(\"third\")   # this should appear in the source snippet\n    ValueError: third\nGot:\n    <BLANKLINE>\n**********************************************************************\nFile \"src/sage/repl/attach.py\", line 58, in sage.repl.attach\nFailed example:\n    detach(src)\nExpected nothing\nGot:\n    Traceback (most recent call last):\n      File \"<doctest sage.repl.attach[13]>\", line 2, in <module>\n        attach(src)\n      File \"sage/misc/lazy_import.pyx\", line 354, in sage.misc.lazy_import.LazyImport.__call__ (build/cythonized/sage/misc/lazy_import.c:3683)\n        return self.get_object()(*args, **kwds)\n      File \"/home/u1/chapoton/sage3/local/lib/python3.6/site-packages/sage/repl/attach.py\", line 356, in attach\n        load(filename, globals(), attach=True)\n      File \"/home/u1/chapoton/sage3/local/lib/python3.6/site-packages/sage/repl/load.py\", line 266, in load\n        exec(code, globals)\n      File \"/home/u1/chapoton/.sage/temp/atlas/6848/foobar.sage8jw3wb2i.py\", line 7, in <module>\n        raise ValueError(\"third\")   # this should appear in the source snippet\n    ValueError: third\n```",
    "created_at": "2019-02-25T14:43:41Z",
    "issue": "https://github.com/sagemath/sage/issues/26881",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/26881#issuecomment-416561",
    "user": "https://github.com/fchapoton"
}
```

<a id='comment:8'></a>
I still get

```
sage -t --long src/sage/repl/attach.py  # 4 doctests failed
```
namely

```
sage -t --long src/sage/repl/attach.py
**********************************************************************
File "src/sage/repl/attach.py", line 36, in sage.repl.attach
Failed example:
    try:
        attach(src)
    except Exception:
        traceback.print_exc()
Expected:
    Traceback (most recent call last):
    ...
        exec(preparse_file(f.read()) + "\n", globals)
      File "<string>", line 3, in <module>
    ValueError: third
Got:
    <BLANKLINE>
**********************************************************************
File "src/sage/repl/attach.py", line 45, in sage.repl.attach
Failed example:
    detach(src)
Expected nothing
Got:
    Traceback (most recent call last):
      File "<doctest sage.repl.attach[10]>", line 2, in <module>
        attach(src)
      File "sage/misc/lazy_import.pyx", line 354, in sage.misc.lazy_import.LazyImport.__call__ (build/cythonized/sage/misc/lazy_import.c:3683)
        return self.get_object()(*args, **kwds)
      File "/home/u1/chapoton/sage3/local/lib/python3.6/site-packages/sage/repl/attach.py", line 356, in attach
        load(filename, globals(), attach=True)
      File "/home/u1/chapoton/sage3/local/lib/python3.6/site-packages/sage/repl/load.py", line 272, in load
        exec(preparse_file(f.read()) + "\n", globals)
      File "<string>", line 3, in <module>
    ValueError: third
**********************************************************************
File "src/sage/repl/attach.py", line 48, in sage.repl.attach
Failed example:
    try:
        attach(src)
    except Exception:
        traceback.print_exc()
Expected:
    Traceback (most recent call last):
    ...
        exec(code, globals)
      File ".../foobar.sage....py", line ..., in <module>
        raise ValueError("third")   # this should appear in the source snippet
    ValueError: third
Got:
    <BLANKLINE>
**********************************************************************
File "src/sage/repl/attach.py", line 58, in sage.repl.attach
Failed example:
    detach(src)
Expected nothing
Got:
    Traceback (most recent call last):
      File "<doctest sage.repl.attach[13]>", line 2, in <module>
        attach(src)
      File "sage/misc/lazy_import.pyx", line 354, in sage.misc.lazy_import.LazyImport.__call__ (build/cythonized/sage/misc/lazy_import.c:3683)
        return self.get_object()(*args, **kwds)
      File "/home/u1/chapoton/sage3/local/lib/python3.6/site-packages/sage/repl/attach.py", line 356, in attach
        load(filename, globals(), attach=True)
      File "/home/u1/chapoton/sage3/local/lib/python3.6/site-packages/sage/repl/load.py", line 266, in load
        exec(code, globals)
      File "/home/u1/chapoton/.sage/temp/atlas/6848/foobar.sage8jw3wb2i.py", line 7, in <module>
        raise ValueError("third")   # this should appear in the source snippet
    ValueError: third
```



---

archive/issue_comments_416562.json:
```json
{
    "body": "**Changing commit** from \"[13b9f224e8b2860a7e15289331e010f06f4387cf](https://github.com/sagemath/sagetrac-mirror/commit/13b9f224e8b2860a7e15289331e010f06f4387cf)\" to \"\".",
    "created_at": "2019-02-25T14:43:41Z",
    "issue": "https://github.com/sagemath/sage/issues/26881",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/26881#issuecomment-416562",
    "user": "https://github.com/fchapoton"
}
```

**Changing commit** from "[13b9f224e8b2860a7e15289331e010f06f4387cf](https://github.com/sagemath/sagetrac-mirror/commit/13b9f224e8b2860a7e15289331e010f06f4387cf)" to "".



---

archive/issue_comments_416563.json:
```json
{
    "body": "<a id='comment:9'></a>\nI don't get that `attach.py` tests pass (as the whole module) in `py2` and `py3` on my computers. Do you use optional modules ?",
    "created_at": "2019-02-25T15:22:31Z",
    "issue": "https://github.com/sagemath/sage/issues/26881",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/26881#issuecomment-416563",
    "user": "https://github.com/vinklein"
}
```

<a id='comment:9'></a>
I don't get that `attach.py` tests pass (as the whole module) in `py2` and `py3` on my computers. Do you use optional modules ?



---

archive/issue_comments_416564.json:
```json
{
    "body": "<a id='comment:10'></a>\nindeed, the tests pass when run alone on the patchbot machine and another machine. So they only fail in the patchbot run.\n\nNote that the failures seems to be a shift in the answers: each doctests receives the output of the previous doctest..",
    "created_at": "2019-02-25T15:25:59Z",
    "issue": "https://github.com/sagemath/sage/issues/26881",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/26881#issuecomment-416564",
    "user": "https://github.com/fchapoton"
}
```

<a id='comment:10'></a>
indeed, the tests pass when run alone on the patchbot machine and another machine. So they only fail in the patchbot run.

Note that the failures seems to be a shift in the answers: each doctests receives the output of the previous doctest..
