# Issue 34516: Large Cremona database construction failure

archive/issues_034279.json:
```json
{
    "assignees": [],
    "body": "<div id=\"comment:0\"></div>\n\nI attempted to build the large Cremona database with sagemath 9.6 and sqlite 3.36.0 on a Fedora 36 x86_64 machine, as follows:\n\n```\nimport sage.databases.cremona\nc = sage.databases.cremona.LargeCremonaDatabase('cremona', False, True)\nc._init_from_ftpdata('ecdata-2019-10-29')\n```\nThe attempt failed at the very end.  This is the last of the output:\n\n```\nInserting allgens.90000-99999\nCommitting...\nTraceback (most recent call last):\n  File \"/builddir/build/BUILD/sage-9.6/cremona.sage.py\", line 10, in <module>\n    c._init_from_ftpdata('ecdata-2019-10-29')\n  File \"/builddir/build/BUILDROOT/sagemath-9.6-4.fc38.x86_64/usr/lib64/python3.11/site-packages/sage/databases/cremona.py\", line 1397, in _init_from_ftpdata\n    self.vacuum()\n  File \"/builddir/build/BUILDROOT/sagemath-9.6-4.fc38.x86_64/usr/lib64/python3.11/site-packages/sage/databases/sql_db.py\", line 2180, in vacuum\n    self.__connection__.execute('VACUUM')\nsqlite3.OperationalError: cannot VACUUM from within a transaction\n```\nThe phrase \"from within a transaction\" suggests a missing commit.  Indeed, unlike `_init_degphi` and `_init_allbsd`, which both print the \"Committing...\" message and then call `self.commit()`, `_init_allgens` just prints the message but doesn't call commit.  This patch adds the missing commit.  With this change, I was able to build the database successfully.\n\nComponent: **elliptic curves**\n\nKeywords: **cremona database**\n\nBranch/Commit: **[u/gh-jamesjer/large_cremona_database_construction_failure](https://github.com/sagemath/sagetrac-mirror/tree/u/gh-jamesjer/large_cremona_database_construction_failure) @ [`0a2c5be`](https://github.com/sagemath/sagetrac-mirror/commit/0a2c5bec0384e8e126c6d955cd4b3aa2ace55d99)**\n\n_Issue created by migration from https://trac.sagemath.org/ticket/34516_\n\n",
    "created_at": "2022-09-09T20:31:40Z",
    "labels": [
        "https://github.com/sagemath/sage/labels/c%3A%20elliptic%20curves",
        "https://github.com/sagemath/sage/labels/p%3A%20minor%20/%204",
        "https://github.com/sagemath/sage/labels/bug",
        "https://github.com/sagemath/sage/labels/c%3A%20databases",
        "https://github.com/sagemath/sage/labels/needs%20review"
    ],
    "reactions": [],
    "repository": "https://github.com/sagemath/sage",
    "title": "Large Cremona database construction failure",
    "type": "issue",
    "updated_at": "2023-01-29T23:06:23Z",
    "url": "https://github.com/sagemath/sage/issues/34516",
    "user": "https://github.com/jamesjer"
}
```
<div id="comment:0"></div>

I attempted to build the large Cremona database with sagemath 9.6 and sqlite 3.36.0 on a Fedora 36 x86_64 machine, as follows:

```
import sage.databases.cremona
c = sage.databases.cremona.LargeCremonaDatabase('cremona', False, True)
c._init_from_ftpdata('ecdata-2019-10-29')
```
The attempt failed at the very end.  This is the last of the output:

```
Inserting allgens.90000-99999
Committing...
Traceback (most recent call last):
  File "/builddir/build/BUILD/sage-9.6/cremona.sage.py", line 10, in <module>
    c._init_from_ftpdata('ecdata-2019-10-29')
  File "/builddir/build/BUILDROOT/sagemath-9.6-4.fc38.x86_64/usr/lib64/python3.11/site-packages/sage/databases/cremona.py", line 1397, in _init_from_ftpdata
    self.vacuum()
  File "/builddir/build/BUILDROOT/sagemath-9.6-4.fc38.x86_64/usr/lib64/python3.11/site-packages/sage/databases/sql_db.py", line 2180, in vacuum
    self.__connection__.execute('VACUUM')
sqlite3.OperationalError: cannot VACUUM from within a transaction
```
The phrase "from within a transaction" suggests a missing commit.  Indeed, unlike `_init_degphi` and `_init_allbsd`, which both print the "Committing..." message and then call `self.commit()`, `_init_allgens` just prints the message but doesn't call commit.  This patch adds the missing commit.  With this change, I was able to build the database successfully.

Component: **elliptic curves**

Keywords: **cremona database**

Branch/Commit: **[u/gh-jamesjer/large_cremona_database_construction_failure](https://github.com/sagemath/sagetrac-mirror/tree/u/gh-jamesjer/large_cremona_database_construction_failure) @ [`0a2c5be`](https://github.com/sagemath/sagetrac-mirror/commit/0a2c5bec0384e8e126c6d955cd4b3aa2ace55d99)**

_Issue created by migration from https://trac.sagemath.org/ticket/34516_





---

archive/issue_events_469170.json:
```json
{
    "actor": "https://github.com/jamesjer",
    "created_at": "2022-09-09T20:31:40Z",
    "event": "milestoned",
    "issue": "https://github.com/sagemath/sage/issues/34516",
    "milestone_number": null,
    "milestone_title": "sage-9.8",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/34516#event-469170"
}
```



---

archive/issue_events_469171.json:
```json
{
    "actor": "https://github.com/jamesjer",
    "created_at": "2022-09-09T20:31:40Z",
    "event": "labeled",
    "issue": "https://github.com/sagemath/sage/issues/34516",
    "label": "https://github.com/sagemath/sage/labels/p%3A%20major%20/%203",
    "label_color": "ffbb00",
    "label_name": "p: major / 3",
    "label_text_color": "ffffff",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/34516#event-469171"
}
```



---

archive/issue_events_469172.json:
```json
{
    "actor": "https://github.com/jamesjer",
    "created_at": "2022-09-09T20:59:20Z",
    "event": "labeled",
    "issue": "https://github.com/sagemath/sage/issues/34516",
    "label": "https://github.com/sagemath/sage/labels/c%3A%20elliptic%20curves",
    "label_color": "0000ff",
    "label_name": "c: elliptic curves",
    "label_text_color": "ffffff",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/34516#event-469172"
}
```



---

archive/issue_events_469173.json:
```json
{
    "actor": "https://github.com/jamesjer",
    "created_at": "2022-09-09T20:59:20Z",
    "event": "labeled",
    "issue": "https://github.com/sagemath/sage/issues/34516",
    "label": "https://github.com/sagemath/sage/labels/bug",
    "label_color": "d73a4a",
    "label_name": "bug",
    "label_text_color": "ffffff",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/34516#event-469173"
}
```



---

archive/issue_events_469174.json:
```json
{
    "actor": "https://github.com/jamesjer",
    "created_at": "2022-09-09T20:59:20Z",
    "event": "unlabeled",
    "issue": "https://github.com/sagemath/sage/issues/34516",
    "label": "https://github.com/sagemath/sage/labels/p%3A%20major%20/%203",
    "label_color": "ffbb00",
    "label_name": "p: major / 3",
    "label_text_color": "ffffff",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/34516#event-469174"
}
```



---

archive/issue_events_469175.json:
```json
{
    "actor": "https://github.com/jamesjer",
    "created_at": "2022-09-09T20:59:20Z",
    "event": "labeled",
    "issue": "https://github.com/sagemath/sage/issues/34516",
    "label": "https://github.com/sagemath/sage/labels/p%3A%20minor%20/%204",
    "label_color": "ffe799",
    "label_name": "p: minor / 4",
    "label_text_color": "ffffff",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/34516#event-469175"
}
```



---

archive/issue_comments_557732.json:
```json
{
    "body": "Description changed:\n``````diff\n--- \n+++ \n@@ -1 +1,22 @@\n+I attempted to build the large Cremona database with sagemath 9.6 and sqlite 3.36.0 on a Fedora 36 x86_64 machine, as follows:\n \n+```\n+import sage.databases.cremona\n+c = sage.databases.cremona.LargeCremonaDatabase('cremona', False, True)\n+c._init_from_ftpdata('ecdata-2019-10-29')\n+```\n+The attempt failed at the very end.  This is the last of the output:\n+\n+```\n+Inserting allgens.90000-99999\n+Committing...\n+Traceback (most recent call last):\n+  File \"/builddir/build/BUILD/sage-9.6/cremona.sage.py\", line 10, in <module>\n+    c._init_from_ftpdata('ecdata-2019-10-29')\n+  File \"/builddir/build/BUILDROOT/sagemath-9.6-4.fc38.x86_64/usr/lib64/python3.11/site-packages/sage/databases/cremona.py\", line 1397, in _init_from_ftpdata\n+    self.vacuum()\n+  File \"/builddir/build/BUILDROOT/sagemath-9.6-4.fc38.x86_64/usr/lib64/python3.11/site-packages/sage/databases/sql_db.py\", line 2180, in vacuum\n+    self.__connection__.execute('VACUUM')\n+sqlite3.OperationalError: cannot VACUUM from within a transaction\n+```\n+The phrase \"from within a transaction\" suggests a missing commit.  Indeed, unlike `_init_degphi` and `_init_allbsd`, which both print the \"Committing...\" message and then call `self.commit()`, `_init_allgens` just prints the message but doesn't call commit.  This patch adds the missing commit.  With this change, I was able to build the database successfully.\n``````\n",
    "created_at": "2022-09-09T20:59:20Z",
    "formatter": "markdown",
    "issue": "https://github.com/sagemath/sage/issues/34516",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/34516#issuecomment-557732",
    "user": "https://github.com/jamesjer"
}
```

Description changed:
``````diff
--- 
+++ 
@@ -1 +1,22 @@
+I attempted to build the large Cremona database with sagemath 9.6 and sqlite 3.36.0 on a Fedora 36 x86_64 machine, as follows:
 
+```
+import sage.databases.cremona
+c = sage.databases.cremona.LargeCremonaDatabase('cremona', False, True)
+c._init_from_ftpdata('ecdata-2019-10-29')
+```
+The attempt failed at the very end.  This is the last of the output:
+
+```
+Inserting allgens.90000-99999
+Committing...
+Traceback (most recent call last):
+  File "/builddir/build/BUILD/sage-9.6/cremona.sage.py", line 10, in <module>
+    c._init_from_ftpdata('ecdata-2019-10-29')
+  File "/builddir/build/BUILDROOT/sagemath-9.6-4.fc38.x86_64/usr/lib64/python3.11/site-packages/sage/databases/cremona.py", line 1397, in _init_from_ftpdata
+    self.vacuum()
+  File "/builddir/build/BUILDROOT/sagemath-9.6-4.fc38.x86_64/usr/lib64/python3.11/site-packages/sage/databases/sql_db.py", line 2180, in vacuum
+    self.__connection__.execute('VACUUM')
+sqlite3.OperationalError: cannot VACUUM from within a transaction
+```
+The phrase "from within a transaction" suggests a missing commit.  Indeed, unlike `_init_degphi` and `_init_allbsd`, which both print the "Committing..." message and then call `self.commit()`, `_init_allgens` just prints the message but doesn't call commit.  This patch adds the missing commit.  With this change, I was able to build the database successfully.
``````




---

archive/issue_comments_557733.json:
```json
{
    "body": "Changed keywords from none to **cremona database**",
    "created_at": "2022-09-09T20:59:20Z",
    "formatter": "markdown",
    "issue": "https://github.com/sagemath/sage/issues/34516",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/34516#issuecomment-557733",
    "user": "https://github.com/jamesjer"
}
```

Changed keywords from none to **cremona database**



---

archive/issue_events_469176.json:
```json
{
    "actor": "https://github.com/jamesjer",
    "created_at": "2022-09-09T20:59:20Z",
    "event": "labeled",
    "issue": "https://github.com/sagemath/sage/issues/34516",
    "label": "https://github.com/sagemath/sage/labels/c%3A%20databases",
    "label_color": "0000ff",
    "label_name": "c: databases",
    "label_text_color": "ffffff",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/34516#event-469176"
}
```



---

archive/issue_comments_557734.json:
```json
{
    "body": "Branch: **[u/gh-jamesjer/large_cremona_database_construction_failure](https://github.com/sagemath/sagetrac-mirror/tree/u/gh-jamesjer/large_cremona_database_construction_failure)**",
    "created_at": "2022-09-09T21:04:32Z",
    "formatter": "markdown",
    "issue": "https://github.com/sagemath/sage/issues/34516",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/34516#issuecomment-557734",
    "user": "https://github.com/jamesjer"
}
```

Branch: **[u/gh-jamesjer/large_cremona_database_construction_failure](https://github.com/sagemath/sagetrac-mirror/tree/u/gh-jamesjer/large_cremona_database_construction_failure)**



---

archive/issue_comments_557735.json:
```json
{
    "body": "<div id=\"comment:3\"></div>\n\nNew commits:\n<table><tr><td><a href=\"https://github.com/sagemath/sagetrac-mirror/commit/0a2c5bec0384e8e126c6d955cd4b3aa2ace55d99\"><code>0a2c5be</code></a></td><td><code>Add missing commit to LargeCremonaDatabase._init_allgens</code></td></tr></table>\n",
    "created_at": "2022-09-09T21:07:40Z",
    "formatter": "markdown",
    "issue": "https://github.com/sagemath/sage/issues/34516",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/34516#issuecomment-557735",
    "user": "https://github.com/jamesjer"
}
```

<div id="comment:3"></div>

New commits:
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/0a2c5bec0384e8e126c6d955cd4b3aa2ace55d99"><code>0a2c5be</code></a></td><td><code>Add missing commit to LargeCremonaDatabase._init_allgens</code></td></tr></table>




---

archive/issue_comments_557736.json:
```json
{
    "body": "Commit: **[`0a2c5be`](https://github.com/sagemath/sagetrac-mirror/commit/0a2c5bec0384e8e126c6d955cd4b3aa2ace55d99)**",
    "created_at": "2022-09-09T21:07:40Z",
    "formatter": "markdown",
    "issue": "https://github.com/sagemath/sage/issues/34516",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/34516#issuecomment-557736",
    "user": "https://github.com/jamesjer"
}
```

Commit: **[`0a2c5be`](https://github.com/sagemath/sagetrac-mirror/commit/0a2c5bec0384e8e126c6d955cd4b3aa2ace55d99)**



---

archive/issue_events_469177.json:
```json
{
    "actor": "https://github.com/jamesjer",
    "created_at": "2022-09-09T21:07:40Z",
    "event": "labeled",
    "issue": "https://github.com/sagemath/sage/issues/34516",
    "label": "https://github.com/sagemath/sage/labels/needs%20review",
    "label_color": "7fff00",
    "label_name": "needs review",
    "label_text_color": "ffffff",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/34516#event-469177"
}
```



---

archive/issue_events_469178.json:
```json
{
    "actor": "https://github.com/mkoeppe",
    "created_at": "2023-01-29T23:06:23Z",
    "event": "demilestoned",
    "issue": "https://github.com/sagemath/sage/issues/34516",
    "milestone_number": null,
    "milestone_title": "sage-9.8",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/34516#event-469178"
}
```
