# Issue 8448: doc/common/builder.py doctests write files in Sage tree

archive/issues_008448.json:
```json
{
    "body": "I am using a system-wide install, so I don't have write access in the Sage tree.  When I run `sage -testall`, I get the following errors.  (More may come; it's only been running a few minutes. :-)\n\n```\nsage -t  \"devel/sage/doc/common/builder.py\"                 \n**********************************************************************\nFile \"/share/apps/contrib/sage-4.3.3/devel/sage/doc/common/builder.py\", line 157:\n    sage: b = builder.DocBuilder('tutorial')\nException raised:\n    Traceback (most recent call last):\n      File \"/share/apps/contrib/sage-4.3.3/local/bin/ncadoctest.py\", line 1231, in run_one_test\n        self.run_one_example(test, example, filename, compileflags)\n      File \"/share/apps/contrib/sage-4.3.3/local/bin/sagedoctest.py\", line 38, in run_one_example\n        OrigDocTestRunner.run_one_example(self, test, example, filename, compileflags)\n      File \"/share/apps/contrib/sage-4.3.3/local/bin/ncadoctest.py\", line 1172, in run_one_example\n        compileflags, 1) in test.globs\n      File \"<doctest __main__.example_4[3]>\", line 1, in <module>\n        b = builder.DocBuilder('tutorial')###line 157:\n    sage: b = builder.DocBuilder('tutorial')\n      File \"/share/apps/contrib/sage-4.3.3/devel/sage/doc/common/builder.py\", line 145, in __init__\n        mkdir(os.path.join(self.dir, \"static\"))\n      File \"/share/apps/contrib/sage-4.3.3/devel/sage/doc/common/builder.py\", line 55, in mkdir\n        os.makedirs(path)\n      File \"/share/apps/contrib/sage-4.3.3/local/lib/python2.6/os.py\", line 157, in makedirs\n        mkdir(name, mode)\n    OSError: [Errno 13] Permission denied: '/share/apps/contrib/sage-4.3.3/devel/sage/doc/en/tutorial/static'\n**********************************************************************\nFile \"/share/apps/contrib/sage-4.3.3/devel/sage/doc/common/builder.py\", line 158:\n    sage: b._output_dir('html')\nException raised:\n    Traceback (most recent call last):\n      File \"/share/apps/contrib/sage-4.3.3/local/bin/ncadoctest.py\", line 1231, in run_one_test\n        self.run_one_example(test, example, filename, compileflags)\n      File \"/share/apps/contrib/sage-4.3.3/local/bin/sagedoctest.py\", line 38, in run_one_example\n        OrigDocTestRunner.run_one_example(self, test, example, filename, compileflags)\n      File \"/share/apps/contrib/sage-4.3.3/local/bin/ncadoctest.py\", line 1172, in run_one_example\n        compileflags, 1) in test.globs\n      File \"<doctest __main__.example_4[4]>\", line 1, in <module>\n        b._output_dir('html')###line 158:\n    sage: b._output_dir('html')\n    NameError: name 'b' is not defined\n**********************************************************************\nFile \"/share/apps/contrib/sage-4.3.3/devel/sage/doc/common/builder.py\", line 172:\n    sage: b = builder.DocBuilder('tutorial')\nException raised:\n    Traceback (most recent call last):\n      File \"/share/apps/contrib/sage-4.3.3/local/bin/ncadoctest.py\", line 1231, in run_one_test\n        self.run_one_example(test, example, filename, compileflags)\n      File \"/share/apps/contrib/sage-4.3.3/local/bin/sagedoctest.py\", line 38, in run_one_example\n        OrigDocTestRunner.run_one_example(self, test, example, filename, compileflags)\n      File \"/share/apps/contrib/sage-4.3.3/local/bin/ncadoctest.py\", line 1172, in run_one_example\n        compileflags, 1) in test.globs\n      File \"<doctest __main__.example_5[3]>\", line 1, in <module>\n        b = builder.DocBuilder('tutorial')###line 172:\n    sage: b = builder.DocBuilder('tutorial')\n      File \"/share/apps/contrib/sage-4.3.3/devel/sage/doc/common/builder.py\", line 145, in __init__\n        mkdir(os.path.join(self.dir, \"static\"))\n      File \"/share/apps/contrib/sage-4.3.3/devel/sage/doc/common/builder.py\", line 55, in mkdir\n        os.makedirs(path)\n      File \"/share/apps/contrib/sage-4.3.3/local/lib/python2.6/os.py\", line 157, in makedirs\n        mkdir(name, mode)\n    OSError: [Errno 13] Permission denied: '/share/apps/contrib/sage-4.3.3/devel/sage/doc/en/tutorial/static'\n**********************************************************************\nFile \"/share/apps/contrib/sage-4.3.3/devel/sage/doc/common/builder.py\", line 173:\n    sage: b._doctrees_dir()\nException raised:\n    Traceback (most recent call last):\n      File \"/share/apps/contrib/sage-4.3.3/local/bin/ncadoctest.py\", line 1231, in run_one_test\n        self.run_one_example(test, example, filename, compileflags)\n      File \"/share/apps/contrib/sage-4.3.3/local/bin/sagedoctest.py\", line 38, in run_one_example\n        OrigDocTestRunner.run_one_example(self, test, example, filename, compileflags)\n      File \"/share/apps/contrib/sage-4.3.3/local/bin/ncadoctest.py\", line 1172, in run_one_example\n        compileflags, 1) in test.globs\n      File \"<doctest __main__.example_5[4]>\", line 1, in <module>\n        b._doctrees_dir()###line 173:\n    sage: b._doctrees_dir()\n    NameError: name 'b' is not defined\n**********************************************************************\nFile \"/share/apps/contrib/sage-4.3.3/devel/sage/doc/common/builder.py\", line 185:\n    sage: b = builder.DocBuilder('tutorial')\nException raised:\n    Traceback (most recent call last):\n      File \"/share/apps/contrib/sage-4.3.3/local/bin/ncadoctest.py\", line 1231, in run_one_test\n        self.run_one_example(test, example, filename, compileflags)\n      File \"/share/apps/contrib/sage-4.3.3/local/bin/sagedoctest.py\", line 38, in run_one_example\n        OrigDocTestRunner.run_one_example(self, test, example, filename, compileflags)\n      File \"/share/apps/contrib/sage-4.3.3/local/bin/ncadoctest.py\", line 1172, in run_one_example\n        compileflags, 1) in test.globs\n      File \"<doctest __main__.example_6[3]>\", line 1, in <module>\n        b = builder.DocBuilder('tutorial')###line 185:\n    sage: b = builder.DocBuilder('tutorial')\n      File \"/share/apps/contrib/sage-4.3.3/devel/sage/doc/common/builder.py\", line 145, in __init__\n        mkdir(os.path.join(self.dir, \"static\"))\n      File \"/share/apps/contrib/sage-4.3.3/devel/sage/doc/common/builder.py\", line 55, in mkdir\n        os.makedirs(path)\n      File \"/share/apps/contrib/sage-4.3.3/local/lib/python2.6/os.py\", line 157, in makedirs\n        mkdir(name, mode)\n    OSError: [Errno 13] Permission denied: '/share/apps/contrib/sage-4.3.3/devel/sage/doc/en/tutorial/static'\n**********************************************************************\nFile \"/share/apps/contrib/sage-4.3.3/devel/sage/doc/common/builder.py\", line 186:\n    sage: b._output_formats()\nException raised:\n    Traceback (most recent call last):\n      File \"/share/apps/contrib/sage-4.3.3/local/bin/ncadoctest.py\", line 1231, in run_one_test\n        self.run_one_example(test, example, filename, compileflags)\n      File \"/share/apps/contrib/sage-4.3.3/local/bin/sagedoctest.py\", line 38, in run_one_example\n        OrigDocTestRunner.run_one_example(self, test, example, filename, compileflags)\n      File \"/share/apps/contrib/sage-4.3.3/local/bin/ncadoctest.py\", line 1172, in run_one_example\n        compileflags, 1) in test.globs\n      File \"<doctest __main__.example_6[4]>\", line 1, in <module>\n        b._output_formats()###line 186:\n    sage: b._output_formats()\n    NameError: name 'b' is not defined\n**********************************************************************\nFile \"/share/apps/contrib/sage-4.3.3/devel/sage/doc/common/builder.py\", line 209:\n    sage: b = builder.DocBuilder('tutorial')\nException raised:\n    Traceback (most recent call last):\n      File \"/share/apps/contrib/sage-4.3.3/local/bin/ncadoctest.py\", line 1231, in run_one_test\n        self.run_one_example(test, example, filename, compileflags)\n      File \"/share/apps/contrib/sage-4.3.3/local/bin/sagedoctest.py\", line 38, in run_one_example\n        OrigDocTestRunner.run_one_example(self, test, example, filename, compileflags)\n      File \"/share/apps/contrib/sage-4.3.3/local/bin/ncadoctest.py\", line 1172, in run_one_example\n        compileflags, 1) in test.globs\n      File \"<doctest __main__.example_7[3]>\", line 1, in <module>\n        b = builder.DocBuilder('tutorial')###line 209:\n    sage: b = builder.DocBuilder('tutorial')\n      File \"/share/apps/contrib/sage-4.3.3/devel/sage/doc/common/builder.py\", line 145, in __init__\n        mkdir(os.path.join(self.dir, \"static\"))\n      File \"/share/apps/contrib/sage-4.3.3/devel/sage/doc/common/builder.py\", line 55, in mkdir\n        os.makedirs(path)\n      File \"/share/apps/contrib/sage-4.3.3/local/lib/python2.6/os.py\", line 157, in makedirs\n        mkdir(name, mode)\n    OSError: [Errno 13] Permission denied: '/share/apps/contrib/sage-4.3.3/devel/sage/doc/en/tutorial/static'\n**********************************************************************\n4 items had failures:\n   2 of   5 in __main__.example_4\n   2 of   5 in __main__.example_5\n   2 of   5 in __main__.example_6\n   1 of   4 in __main__.example_7\n***Test Failed*** 7 failures.\nFor whitespace errors, see the file /home/rwh4s/.sage//tmp/.doctest_builder.py\n [6.9 s]\n```\n\nThis issue was reported to [sage-devel](http://groups.google.com/group/sage-devel/browse_thread/thread/be25c49816581da4).\n\n**Assignee:** mvngu\n\n**CC:**  @dimpase\n\n**Keywords:** builder.py, doctest, system-wide\n\nIssue created by migration from https://trac.sagemath.org/ticket/8448\n\n",
    "closed_at": "2020-10-31T07:34:19Z",
    "created_at": "2010-03-05T17:13:21Z",
    "labels": [
        "component: documentation",
        "bug",
        "invalid"
    ],
    "title": "doc/common/builder.py doctests write files in Sage tree",
    "type": "issue",
    "url": "https://github.com/sagemath/sage/issues/8448",
    "user": "https://github.com/rhinton"
}
```
I am using a system-wide install, so I don't have write access in the Sage tree.  When I run `sage -testall`, I get the following errors.  (More may come; it's only been running a few minutes. :-)

```
sage -t  "devel/sage/doc/common/builder.py"                 
**********************************************************************
File "/share/apps/contrib/sage-4.3.3/devel/sage/doc/common/builder.py", line 157:
    sage: b = builder.DocBuilder('tutorial')
Exception raised:
    Traceback (most recent call last):
      File "/share/apps/contrib/sage-4.3.3/local/bin/ncadoctest.py", line 1231, in run_one_test
        self.run_one_example(test, example, filename, compileflags)
      File "/share/apps/contrib/sage-4.3.3/local/bin/sagedoctest.py", line 38, in run_one_example
        OrigDocTestRunner.run_one_example(self, test, example, filename, compileflags)
      File "/share/apps/contrib/sage-4.3.3/local/bin/ncadoctest.py", line 1172, in run_one_example
        compileflags, 1) in test.globs
      File "<doctest __main__.example_4[3]>", line 1, in <module>
        b = builder.DocBuilder('tutorial')###line 157:
    sage: b = builder.DocBuilder('tutorial')
      File "/share/apps/contrib/sage-4.3.3/devel/sage/doc/common/builder.py", line 145, in __init__
        mkdir(os.path.join(self.dir, "static"))
      File "/share/apps/contrib/sage-4.3.3/devel/sage/doc/common/builder.py", line 55, in mkdir
        os.makedirs(path)
      File "/share/apps/contrib/sage-4.3.3/local/lib/python2.6/os.py", line 157, in makedirs
        mkdir(name, mode)
    OSError: [Errno 13] Permission denied: '/share/apps/contrib/sage-4.3.3/devel/sage/doc/en/tutorial/static'
**********************************************************************
File "/share/apps/contrib/sage-4.3.3/devel/sage/doc/common/builder.py", line 158:
    sage: b._output_dir('html')
Exception raised:
    Traceback (most recent call last):
      File "/share/apps/contrib/sage-4.3.3/local/bin/ncadoctest.py", line 1231, in run_one_test
        self.run_one_example(test, example, filename, compileflags)
      File "/share/apps/contrib/sage-4.3.3/local/bin/sagedoctest.py", line 38, in run_one_example
        OrigDocTestRunner.run_one_example(self, test, example, filename, compileflags)
      File "/share/apps/contrib/sage-4.3.3/local/bin/ncadoctest.py", line 1172, in run_one_example
        compileflags, 1) in test.globs
      File "<doctest __main__.example_4[4]>", line 1, in <module>
        b._output_dir('html')###line 158:
    sage: b._output_dir('html')
    NameError: name 'b' is not defined
**********************************************************************
File "/share/apps/contrib/sage-4.3.3/devel/sage/doc/common/builder.py", line 172:
    sage: b = builder.DocBuilder('tutorial')
Exception raised:
    Traceback (most recent call last):
      File "/share/apps/contrib/sage-4.3.3/local/bin/ncadoctest.py", line 1231, in run_one_test
        self.run_one_example(test, example, filename, compileflags)
      File "/share/apps/contrib/sage-4.3.3/local/bin/sagedoctest.py", line 38, in run_one_example
        OrigDocTestRunner.run_one_example(self, test, example, filename, compileflags)
      File "/share/apps/contrib/sage-4.3.3/local/bin/ncadoctest.py", line 1172, in run_one_example
        compileflags, 1) in test.globs
      File "<doctest __main__.example_5[3]>", line 1, in <module>
        b = builder.DocBuilder('tutorial')###line 172:
    sage: b = builder.DocBuilder('tutorial')
      File "/share/apps/contrib/sage-4.3.3/devel/sage/doc/common/builder.py", line 145, in __init__
        mkdir(os.path.join(self.dir, "static"))
      File "/share/apps/contrib/sage-4.3.3/devel/sage/doc/common/builder.py", line 55, in mkdir
        os.makedirs(path)
      File "/share/apps/contrib/sage-4.3.3/local/lib/python2.6/os.py", line 157, in makedirs
        mkdir(name, mode)
    OSError: [Errno 13] Permission denied: '/share/apps/contrib/sage-4.3.3/devel/sage/doc/en/tutorial/static'
**********************************************************************
File "/share/apps/contrib/sage-4.3.3/devel/sage/doc/common/builder.py", line 173:
    sage: b._doctrees_dir()
Exception raised:
    Traceback (most recent call last):
      File "/share/apps/contrib/sage-4.3.3/local/bin/ncadoctest.py", line 1231, in run_one_test
        self.run_one_example(test, example, filename, compileflags)
      File "/share/apps/contrib/sage-4.3.3/local/bin/sagedoctest.py", line 38, in run_one_example
        OrigDocTestRunner.run_one_example(self, test, example, filename, compileflags)
      File "/share/apps/contrib/sage-4.3.3/local/bin/ncadoctest.py", line 1172, in run_one_example
        compileflags, 1) in test.globs
      File "<doctest __main__.example_5[4]>", line 1, in <module>
        b._doctrees_dir()###line 173:
    sage: b._doctrees_dir()
    NameError: name 'b' is not defined
**********************************************************************
File "/share/apps/contrib/sage-4.3.3/devel/sage/doc/common/builder.py", line 185:
    sage: b = builder.DocBuilder('tutorial')
Exception raised:
    Traceback (most recent call last):
      File "/share/apps/contrib/sage-4.3.3/local/bin/ncadoctest.py", line 1231, in run_one_test
        self.run_one_example(test, example, filename, compileflags)
      File "/share/apps/contrib/sage-4.3.3/local/bin/sagedoctest.py", line 38, in run_one_example
        OrigDocTestRunner.run_one_example(self, test, example, filename, compileflags)
      File "/share/apps/contrib/sage-4.3.3/local/bin/ncadoctest.py", line 1172, in run_one_example
        compileflags, 1) in test.globs
      File "<doctest __main__.example_6[3]>", line 1, in <module>
        b = builder.DocBuilder('tutorial')###line 185:
    sage: b = builder.DocBuilder('tutorial')
      File "/share/apps/contrib/sage-4.3.3/devel/sage/doc/common/builder.py", line 145, in __init__
        mkdir(os.path.join(self.dir, "static"))
      File "/share/apps/contrib/sage-4.3.3/devel/sage/doc/common/builder.py", line 55, in mkdir
        os.makedirs(path)
      File "/share/apps/contrib/sage-4.3.3/local/lib/python2.6/os.py", line 157, in makedirs
        mkdir(name, mode)
    OSError: [Errno 13] Permission denied: '/share/apps/contrib/sage-4.3.3/devel/sage/doc/en/tutorial/static'
**********************************************************************
File "/share/apps/contrib/sage-4.3.3/devel/sage/doc/common/builder.py", line 186:
    sage: b._output_formats()
Exception raised:
    Traceback (most recent call last):
      File "/share/apps/contrib/sage-4.3.3/local/bin/ncadoctest.py", line 1231, in run_one_test
        self.run_one_example(test, example, filename, compileflags)
      File "/share/apps/contrib/sage-4.3.3/local/bin/sagedoctest.py", line 38, in run_one_example
        OrigDocTestRunner.run_one_example(self, test, example, filename, compileflags)
      File "/share/apps/contrib/sage-4.3.3/local/bin/ncadoctest.py", line 1172, in run_one_example
        compileflags, 1) in test.globs
      File "<doctest __main__.example_6[4]>", line 1, in <module>
        b._output_formats()###line 186:
    sage: b._output_formats()
    NameError: name 'b' is not defined
**********************************************************************
File "/share/apps/contrib/sage-4.3.3/devel/sage/doc/common/builder.py", line 209:
    sage: b = builder.DocBuilder('tutorial')
Exception raised:
    Traceback (most recent call last):
      File "/share/apps/contrib/sage-4.3.3/local/bin/ncadoctest.py", line 1231, in run_one_test
        self.run_one_example(test, example, filename, compileflags)
      File "/share/apps/contrib/sage-4.3.3/local/bin/sagedoctest.py", line 38, in run_one_example
        OrigDocTestRunner.run_one_example(self, test, example, filename, compileflags)
      File "/share/apps/contrib/sage-4.3.3/local/bin/ncadoctest.py", line 1172, in run_one_example
        compileflags, 1) in test.globs
      File "<doctest __main__.example_7[3]>", line 1, in <module>
        b = builder.DocBuilder('tutorial')###line 209:
    sage: b = builder.DocBuilder('tutorial')
      File "/share/apps/contrib/sage-4.3.3/devel/sage/doc/common/builder.py", line 145, in __init__
        mkdir(os.path.join(self.dir, "static"))
      File "/share/apps/contrib/sage-4.3.3/devel/sage/doc/common/builder.py", line 55, in mkdir
        os.makedirs(path)
      File "/share/apps/contrib/sage-4.3.3/local/lib/python2.6/os.py", line 157, in makedirs
        mkdir(name, mode)
    OSError: [Errno 13] Permission denied: '/share/apps/contrib/sage-4.3.3/devel/sage/doc/en/tutorial/static'
**********************************************************************
4 items had failures:
   2 of   5 in __main__.example_4
   2 of   5 in __main__.example_5
   2 of   5 in __main__.example_6
   1 of   4 in __main__.example_7
***Test Failed*** 7 failures.
For whitespace errors, see the file /home/rwh4s/.sage//tmp/.doctest_builder.py
 [6.9 s]
```

This issue was reported to [sage-devel](http://groups.google.com/group/sage-devel/browse_thread/thread/be25c49816581da4).

**Assignee:** mvngu

**CC:**  @dimpase

**Keywords:** builder.py, doctest, system-wide

Issue created by migration from https://trac.sagemath.org/ticket/8448





---

archive/issue_comments_068773.json:
```json
{
    "body": "**Description changed:**\n``````diff\n--- \n+++ \n@@ -141,3 +141,5 @@\n For whitespace errors, see the file /home/rwh4s/.sage//tmp/.doctest_builder.py\n \t [6.9 s]\n ```\n+\n+This issue was reported to [sage-devel](http://groups.google.com/group/sage-devel/browse_thread/thread/be25c49816581da4).\n``````\n",
    "created_at": "2010-03-05T19:05:32Z",
    "issue": "https://github.com/sagemath/sage/issues/8448",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/8448#issuecomment-68773",
    "user": "https://trac.sagemath.org/admin/accounts/users/mvngu"
}
```

**Description changed:**
``````diff
--- 
+++ 
@@ -141,3 +141,5 @@
 For whitespace errors, see the file /home/rwh4s/.sage//tmp/.doctest_builder.py
 	 [6.9 s]
 ```
+
+This issue was reported to [sage-devel](http://groups.google.com/group/sage-devel/browse_thread/thread/be25c49816581da4).
``````




---

archive/issue_events_059938.json:
```json
{
    "actor": "https://github.com/jdemeyer",
    "created_at": "2013-08-13T15:35:53Z",
    "event": "demilestoned",
    "issue": "https://github.com/sagemath/sage/issues/8448",
    "milestone": "sage-5.11",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/8448#event-59938"
}
```



---

archive/issue_events_059939.json:
```json
{
    "actor": "https://github.com/jdemeyer",
    "created_at": "2013-08-13T15:35:53Z",
    "event": "milestoned",
    "issue": "https://github.com/sagemath/sage/issues/8448",
    "milestone": "sage-5.12",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/8448#event-59939"
}
```



---

archive/issue_events_059940.json:
```json
{
    "actor": "https://trac.sagemath.org/admin/accounts/users/vbraun_spam",
    "created_at": "2014-01-30T21:20:52Z",
    "event": "demilestoned",
    "issue": "https://github.com/sagemath/sage/issues/8448",
    "milestone": "sage-6.1",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/8448#event-59940"
}
```



---

archive/issue_events_059941.json:
```json
{
    "actor": "https://trac.sagemath.org/admin/accounts/users/vbraun_spam",
    "created_at": "2014-01-30T21:20:52Z",
    "event": "milestoned",
    "issue": "https://github.com/sagemath/sage/issues/8448",
    "milestone": "sage-6.2",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/8448#event-59941"
}
```



---

archive/issue_events_059942.json:
```json
{
    "actor": "https://trac.sagemath.org/admin/accounts/users/vbraun_spam",
    "created_at": "2014-05-06T15:20:58Z",
    "event": "demilestoned",
    "issue": "https://github.com/sagemath/sage/issues/8448",
    "milestone": "sage-6.2",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/8448#event-59942"
}
```



---

archive/issue_events_059943.json:
```json
{
    "actor": "https://trac.sagemath.org/admin/accounts/users/vbraun_spam",
    "created_at": "2014-05-06T15:20:58Z",
    "event": "milestoned",
    "issue": "https://github.com/sagemath/sage/issues/8448",
    "milestone": "sage-6.3",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/8448#event-59943"
}
```



---

archive/issue_events_059944.json:
```json
{
    "actor": "https://trac.sagemath.org/admin/accounts/users/vbraun_spam",
    "created_at": "2014-08-10T16:51:03Z",
    "event": "demilestoned",
    "issue": "https://github.com/sagemath/sage/issues/8448",
    "milestone": "sage-6.3",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/8448#event-59944"
}
```



---

archive/issue_events_059945.json:
```json
{
    "actor": "https://trac.sagemath.org/admin/accounts/users/vbraun_spam",
    "created_at": "2014-08-10T16:51:03Z",
    "event": "milestoned",
    "issue": "https://github.com/sagemath/sage/issues/8448",
    "milestone": "sage-6.4",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/8448#event-59945"
}
```



---

archive/issue_comments_068774.json:
```json
{
    "body": "**Description changed:**\n``````diff\n--- \n+++ \n@@ -139,7 +139,7 @@\n    1 of   4 in __main__.example_7\n ***Test Failed*** 7 failures.\n For whitespace errors, see the file /home/rwh4s/.sage//tmp/.doctest_builder.py\n-\t [6.9 s]\n+ [6.9 s]\n ```\n \n This issue was reported to [sage-devel](http://groups.google.com/group/sage-devel/browse_thread/thread/be25c49816581da4).\n``````\n",
    "created_at": "2015-09-06T16:19:58Z",
    "issue": "https://github.com/sagemath/sage/issues/8448",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/8448#issuecomment-68774",
    "user": "https://github.com/fchapoton"
}
```

**Description changed:**
``````diff
--- 
+++ 
@@ -139,7 +139,7 @@
    1 of   4 in __main__.example_7
 ***Test Failed*** 7 failures.
 For whitespace errors, see the file /home/rwh4s/.sage//tmp/.doctest_builder.py
-	 [6.9 s]
+ [6.9 s]
 ```
 
 This issue was reported to [sage-devel](http://groups.google.com/group/sage-devel/browse_thread/thread/be25c49816581da4).
``````




---

archive/issue_events_059946.json:
```json
{
    "actor": "https://github.com/mkoeppe",
    "created_at": "2020-08-17T16:38:58Z",
    "event": "demilestoned",
    "issue": "https://github.com/sagemath/sage/issues/8448",
    "milestone": "sage-6.4",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/8448#event-59946"
}
```



---

archive/issue_events_059947.json:
```json
{
    "actor": "https://github.com/mkoeppe",
    "created_at": "2020-08-17T16:38:58Z",
    "event": "labeled",
    "issue": "https://github.com/sagemath/sage/issues/8448",
    "label": "needs review",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/8448#event-59947"
}
```



---

archive/issue_comments_068775.json:
```json
{
    "body": "<a id='comment:7'></a>\nOutdated spkg or build system ticket, should be closed",
    "created_at": "2020-08-17T16:38:58Z",
    "issue": "https://github.com/sagemath/sage/issues/8448",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/8448#issuecomment-68775",
    "user": "https://github.com/mkoeppe"
}
```

<a id='comment:7'></a>
Outdated spkg or build system ticket, should be closed



---

archive/issue_events_059948.json:
```json
{
    "actor": "https://github.com/mezzarobba",
    "created_at": "2020-10-31T07:26:44Z",
    "event": "unlabeled",
    "issue": "https://github.com/sagemath/sage/issues/8448",
    "label": "needs review",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/8448#event-59948"
}
```



---

archive/issue_events_059949.json:
```json
{
    "actor": "https://github.com/mezzarobba",
    "created_at": "2020-10-31T07:26:44Z",
    "event": "labeled",
    "issue": "https://github.com/sagemath/sage/issues/8448",
    "label": "positive review",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/8448#event-59949"
}
```



---

archive/issue_events_059950.json:
```json
{
    "actor": "https://github.com/fchapoton",
    "created_at": "2020-10-31T07:34:19Z",
    "event": "unlabeled",
    "issue": "https://github.com/sagemath/sage/issues/8448",
    "label": "positive review",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/8448#event-59950"
}
```



---

archive/issue_events_059951.json:
```json
{
    "actor": "https://github.com/fchapoton",
    "created_at": "2020-10-31T07:34:19Z",
    "event": "closed",
    "issue": "https://github.com/sagemath/sage/issues/8448",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/8448#event-59951"
}
```
