# Issue 14483: Helpful message if GAP fails to load a package

archive/issues_014279.json:
```json
{
    "body": "Very short patch ! I met that problem while trying to run \n\n```\nsage: sage.combinat.designs.block_design.WittDesign(24)\n```\nand I had no idea how to install a gap package in the copy of gap that Sage contains...\n\n\nNathann\n\n**Assignee:** @jdemeyer\n\n**CC:**  @dimpase @vbraun @malb\n\n**Reviewer:** Dmitrii Pasechnik\n\n**Author:** Nathann Cohen\n\n**Merged:** sage-5.10.beta1\n\nIssue created by migration from https://trac.sagemath.org/ticket/14483\n\n",
    "closed_at": "2013-04-30T09:40:18Z",
    "created_at": "2013-04-24T15:54:43Z",
    "labels": [
        "component: combinatorics",
        "bug"
    ],
    "milestone": "https://github.com/sagemath/sage/milestones/sage-5.10",
    "title": "Helpful message if GAP fails to load a package",
    "type": "issue",
    "url": "https://github.com/sagemath/sage/issues/14483",
    "user": "https://github.com/nathanncohen"
}
```
Very short patch ! I met that problem while trying to run 

```
sage: sage.combinat.designs.block_design.WittDesign(24)
```
and I had no idea how to install a gap package in the copy of gap that Sage contains...


Nathann

**Assignee:** @jdemeyer

**CC:**  @dimpase @vbraun @malb

**Reviewer:** Dmitrii Pasechnik

**Author:** Nathann Cohen

**Merged:** sage-5.10.beta1

Issue created by migration from https://trac.sagemath.org/ticket/14483





---

archive/issue_events_126702.json:
```json
{
    "actor": "https://github.com/nathanncohen",
    "created_at": "2013-04-24T15:55:32Z",
    "event": "labeled",
    "issue": "https://github.com/sagemath/sage/issues/14483",
    "label": "needs review",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/14483#event-126702"
}
```



---

archive/issue_comments_177403.json:
```json
{
    "body": "<a id='comment:2'></a>\nThis patch works for me, applied to sage 5.8:\n\n` sage: sage.combinat.designs.block_design.WittDesign(24)`\n\n`Incidence structure with 24 points and 759 block `\n\nHowever, after being prompted to run install_package(\"gap_packages\"), gap_packages-4.5.7 is found. After you updated the spkg was I supposed to find gap_packages-4.6.3 ?",
    "created_at": "2013-04-25T00:49:59Z",
    "issue": "https://github.com/sagemath/sage/issues/14483",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/14483#issuecomment-177403",
    "user": "https://github.com/jeffpferreira"
}
```

<a id='comment:2'></a>
This patch works for me, applied to sage 5.8:

` sage: sage.combinat.designs.block_design.WittDesign(24)`

`Incidence structure with 24 points and 759 block `

However, after being prompted to run install_package("gap_packages"), gap_packages-4.5.7 is found. After you updated the spkg was I supposed to find gap_packages-4.6.3 ?



---

archive/issue_comments_177404.json:
```json
{
    "body": "<a id='comment:3'></a>\nhow does this ticket relate to #14039 ?",
    "created_at": "2013-04-25T04:31:17Z",
    "issue": "https://github.com/sagemath/sage/issues/14483",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/14483#issuecomment-177404",
    "user": "https://github.com/dimpase"
}
```

<a id='comment:3'></a>
how does this ticket relate to #14039 ?



---

archive/issue_events_126703.json:
```json
{
    "actor": "https://github.com/dimpase",
    "created_at": "2013-04-25T04:31:17Z",
    "event": "unlabeled",
    "issue": "https://github.com/sagemath/sage/issues/14483",
    "label": "needs review",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/14483#event-126703"
}
```



---

archive/issue_events_126704.json:
```json
{
    "actor": "https://github.com/dimpase",
    "created_at": "2013-04-25T04:31:17Z",
    "event": "labeled",
    "issue": "https://github.com/sagemath/sage/issues/14483",
    "label": "needs info",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/14483#event-126704"
}
```



---

archive/issue_comments_177405.json:
```json
{
    "body": "**Description changed:**\n``````diff\n--- \n+++ \n@@ -5,7 +5,5 @@\n ```\n and I had no idea how to install a gap package in the copy of gap that Sage contains...\n \n-I also updated the spkg on the way.\n-http://www.steinertriples.fr/gap-4.6.3.p0.spkg\n \n Nathann\n``````\n",
    "created_at": "2013-04-25T04:37:54Z",
    "issue": "https://github.com/sagemath/sage/issues/14483",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/14483#issuecomment-177405",
    "user": "https://github.com/dimpase"
}
```

**Description changed:**
``````diff
--- 
+++ 
@@ -5,7 +5,5 @@
 ```
 and I had no idea how to install a gap package in the copy of gap that Sage contains...
 
-I also updated the spkg on the way.
-http://www.steinertriples.fr/gap-4.6.3.p0.spkg
 
 Nathann
``````




---

archive/issue_events_126705.json:
```json
{
    "actor": "https://github.com/dimpase",
    "created_at": "2013-04-25T04:37:54Z",
    "event": "unlabeled",
    "issue": "https://github.com/sagemath/sage/issues/14483",
    "label": "needs info",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/14483#event-126705"
}
```



---

archive/issue_events_126706.json:
```json
{
    "actor": "https://github.com/dimpase",
    "created_at": "2013-04-25T04:37:54Z",
    "event": "labeled",
    "issue": "https://github.com/sagemath/sage/issues/14483",
    "label": "needs review",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/14483#event-126706"
}
```



---

archive/issue_comments_177406.json:
```json
{
    "body": "<a id='comment:4'></a>\nremoved  http://www.steinertriples.fr/gap-4.6.3.p0.spkg from the ticket description.",
    "created_at": "2013-04-25T04:37:54Z",
    "issue": "https://github.com/sagemath/sage/issues/14483",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/14483#issuecomment-177406",
    "user": "https://github.com/dimpase"
}
```

<a id='comment:4'></a>
removed  http://www.steinertriples.fr/gap-4.6.3.p0.spkg from the ticket description.



---

archive/issue_events_126707.json:
```json
{
    "actor": "https://github.com/dimpase",
    "created_at": "2013-04-25T04:39:23Z",
    "event": "unlabeled",
    "issue": "https://github.com/sagemath/sage/issues/14483",
    "label": "needs review",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/14483#event-126707"
}
```



---

archive/issue_events_126708.json:
```json
{
    "actor": "https://github.com/dimpase",
    "created_at": "2013-04-25T04:39:23Z",
    "event": "labeled",
    "issue": "https://github.com/sagemath/sage/issues/14483",
    "label": "positive review",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/14483#event-126708"
}
```



---

archive/issue_comments_177407.json:
```json
{
    "body": "<a id='comment:5'></a>\nPositive review - the patch works on Sage 4.5.9.beta5 just fine. GAP updates should be dealt with elsewhere.",
    "created_at": "2013-04-25T04:39:23Z",
    "issue": "https://github.com/sagemath/sage/issues/14483",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/14483#issuecomment-177407",
    "user": "https://github.com/dimpase"
}
```

<a id='comment:5'></a>
Positive review - the patch works on Sage 4.5.9.beta5 just fine. GAP updates should be dealt with elsewhere.



---

archive/issue_events_126709.json:
```json
{
    "actor": "https://github.com/dimpase",
    "created_at": "2013-04-25T04:40:13Z",
    "event": "unlabeled",
    "issue": "https://github.com/sagemath/sage/issues/14483",
    "label": "enhancement",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/14483#event-126709"
}
```



---

archive/issue_events_126710.json:
```json
{
    "actor": "https://github.com/dimpase",
    "created_at": "2013-04-25T04:40:13Z",
    "event": "labeled",
    "issue": "https://github.com/sagemath/sage/issues/14483",
    "label": "bug",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/14483#event-126710"
}
```



---

archive/issue_events_126711.json:
```json
{
    "actor": "https://github.com/dimpase",
    "created_at": "2013-04-25T04:40:13Z",
    "event": "unlabeled",
    "issue": "https://github.com/sagemath/sage/issues/14483",
    "label": "component: packages: standard",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/14483#event-126711"
}
```



---

archive/issue_events_126712.json:
```json
{
    "actor": "https://github.com/dimpase",
    "created_at": "2013-04-25T04:40:13Z",
    "event": "labeled",
    "issue": "https://github.com/sagemath/sage/issues/14483",
    "label": "component: combinatorics",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/14483#event-126712"
}
```



---

archive/issue_events_126713.json:
```json
{
    "actor": "https://github.com/jdemeyer",
    "created_at": "2013-04-25T05:21:00Z",
    "event": "renamed",
    "issue": "https://github.com/sagemath/sage/issues/14483",
    "rename": {
        "from": "Update of GAP, and a an helpful message it fails at loading a package",
        "to": "Helpful message if GAP fails to load a package"
    },
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/14483#event-126713"
}
```



---

archive/issue_comments_177408.json:
```json
{
    "body": "**Reviewer:** Dmitrii Pasechnik",
    "created_at": "2013-04-25T05:21:00Z",
    "issue": "https://github.com/sagemath/sage/issues/14483",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/14483#issuecomment-177408",
    "user": "https://github.com/jdemeyer"
}
```

**Reviewer:** Dmitrii Pasechnik



---

archive/issue_comments_177409.json:
```json
{
    "body": "<a id='comment:8'></a>\n> However, after being prompted to run install_package(\"gap_packages\"), gap_packages-4.5.7 is found. After you updated the spkg was I supposed to find gap_packages-4.6.3 ?\n\nNononono, `gap` and `gap_packages` are different spkg. Besides, when you ask Sage to install a package for you it will download the latest \"accepted\" package, so not the one from this ticket `:-)`\n\nNathann",
    "created_at": "2013-04-25T07:25:20Z",
    "issue": "https://github.com/sagemath/sage/issues/14483",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/14483#issuecomment-177409",
    "user": "https://github.com/nathanncohen"
}
```

<a id='comment:8'></a>
> However, after being prompted to run install_package("gap_packages"), gap_packages-4.5.7 is found. After you updated the spkg was I supposed to find gap_packages-4.6.3 ?

Nononono, `gap` and `gap_packages` are different spkg. Besides, when you ask Sage to install a package for you it will download the latest "accepted" package, so not the one from this ticket `:-)`

Nathann



---

archive/issue_comments_177410.json:
```json
{
    "body": "<a id='comment:9'></a>\n> how does this ticket relate to #14039 ?\n\nOops...\n\nNathann",
    "created_at": "2013-04-25T07:25:42Z",
    "issue": "https://github.com/sagemath/sage/issues/14483",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/14483#issuecomment-177410",
    "user": "https://github.com/nathanncohen"
}
```

<a id='comment:9'></a>
> how does this ticket relate to #14039 ?

Oops...

Nathann



---

archive/issue_comments_177411.json:
```json
{
    "body": "<a id='comment:10'></a>\n> Positive review - the patch works on Sage 4.5.9.beta5 just fine.\n\nThaaaaaaanks !\n\n> GAP updates should be dealt with elsewhere.\n\nYepyep. Sorry 'bout that `:-)`\n\nNathann",
    "created_at": "2013-04-25T07:26:08Z",
    "issue": "https://github.com/sagemath/sage/issues/14483",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/14483#issuecomment-177411",
    "user": "https://github.com/nathanncohen"
}
```

<a id='comment:10'></a>
> Positive review - the patch works on Sage 4.5.9.beta5 just fine.

Thaaaaaaanks !

> GAP updates should be dealt with elsewhere.

Yepyep. Sorry 'bout that `:-)`

Nathann



---

archive/issue_comments_177412.json:
```json
{
    "body": "<a id='comment:11'></a>\nDoesn't really matter here, but in general error messages should be kept brief. If you want to show the user some explanation or hints how to get around a potential pitfall you should use warnings so that it is only printed once during the session.",
    "created_at": "2013-04-25T09:28:27Z",
    "issue": "https://github.com/sagemath/sage/issues/14483",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/14483#issuecomment-177412",
    "user": "https://github.com/vbraun"
}
```

<a id='comment:11'></a>
Doesn't really matter here, but in general error messages should be kept brief. If you want to show the user some explanation or hints how to get around a potential pitfall you should use warnings so that it is only printed once during the session.



---

archive/issue_comments_177413.json:
```json
{
    "body": "<a id='comment:12'></a>\nOh, I see. Thanks `:-)`\n\nNathann",
    "created_at": "2013-04-25T09:30:06Z",
    "issue": "https://github.com/sagemath/sage/issues/14483",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/14483#issuecomment-177413",
    "user": "https://github.com/nathanncohen"
}
```

<a id='comment:12'></a>
Oh, I see. Thanks `:-)`

Nathann



---

archive/issue_comments_177414.json:
```json
{
    "body": "<a id='comment:13'></a>\n\n```\nsage -t devel/sage/sage/groups/perm_gps/permgroup.py\n**********************************************************************\nFile \"devel/sage/sage/groups/perm_gps/permgroup.py\", line 152, in sage.groups.perm_gps.permgroup.load_hap\nFailed example:\n    sage.groups.perm_gps.permgroup.load_hap()\nException raised:\n    Traceback (most recent call last):\n      File \"/mazur/release/merger/sage-5.10.beta1/local/lib/python2.7/site-packages/sage/doctest/forker.py\", line 466, in _run\n        self.execute(example, compiled, test.globs)\n      File \"/mazur/release/merger/sage-5.10.beta1/local/lib/python2.7/site-packages/sage/doctest/forker.py\", line 825, in execute\n        exec compiled in globs\n      File \"<doctest sage.groups.perm_gps.permgroup.load_hap[0]>\", line 1, in <module>\n        sage.groups.perm_gps.permgroup.load_hap()\n      File \"/mazur/release/merger/sage-5.10.beta1/local/lib/python2.7/site-packages/sage/groups/perm_gps/permgroup.py\", line 157, in load_hap\n        gap.load_package(\"hap\")\n      File \"/mazur/release/merger/sage-5.10.beta1/local/lib/python2.7/site-packages/sage/interfaces/gap.py\", line 514, in load_package\n        \"install_package(\\\"gap_packages\\\")\"%pkg)\n    RuntimeError: Error loading Gap package hap. You may want to install a collection of GAP packages by installing the 'gap_packages' Sage spkg. If so, then run instal\nl_package(\"gap_packages\")\n**********************************************************************\n```",
    "created_at": "2013-04-25T12:53:34Z",
    "issue": "https://github.com/sagemath/sage/issues/14483",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/14483#issuecomment-177414",
    "user": "https://github.com/jdemeyer"
}
```

<a id='comment:13'></a>

```
sage -t devel/sage/sage/groups/perm_gps/permgroup.py
**********************************************************************
File "devel/sage/sage/groups/perm_gps/permgroup.py", line 152, in sage.groups.perm_gps.permgroup.load_hap
Failed example:
    sage.groups.perm_gps.permgroup.load_hap()
Exception raised:
    Traceback (most recent call last):
      File "/mazur/release/merger/sage-5.10.beta1/local/lib/python2.7/site-packages/sage/doctest/forker.py", line 466, in _run
        self.execute(example, compiled, test.globs)
      File "/mazur/release/merger/sage-5.10.beta1/local/lib/python2.7/site-packages/sage/doctest/forker.py", line 825, in execute
        exec compiled in globs
      File "<doctest sage.groups.perm_gps.permgroup.load_hap[0]>", line 1, in <module>
        sage.groups.perm_gps.permgroup.load_hap()
      File "/mazur/release/merger/sage-5.10.beta1/local/lib/python2.7/site-packages/sage/groups/perm_gps/permgroup.py", line 157, in load_hap
        gap.load_package("hap")
      File "/mazur/release/merger/sage-5.10.beta1/local/lib/python2.7/site-packages/sage/interfaces/gap.py", line 514, in load_package
        "install_package(\"gap_packages\")"%pkg)
    RuntimeError: Error loading Gap package hap. You may want to install a collection of GAP packages by installing the 'gap_packages' Sage spkg. If so, then run instal
l_package("gap_packages")
**********************************************************************
```



---

archive/issue_events_126714.json:
```json
{
    "actor": "https://github.com/jdemeyer",
    "created_at": "2013-04-25T12:53:34Z",
    "event": "unlabeled",
    "issue": "https://github.com/sagemath/sage/issues/14483",
    "label": "positive review",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/14483#event-126714"
}
```



---

archive/issue_events_126715.json:
```json
{
    "actor": "https://github.com/jdemeyer",
    "created_at": "2013-04-25T12:53:34Z",
    "event": "labeled",
    "issue": "https://github.com/sagemath/sage/issues/14483",
    "label": "needs work",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/14483#event-126715"
}
```



---

archive/issue_comments_177415.json:
```json
{
    "body": "<a id='comment:14'></a>\nI agree with Volker that a long warning is better than a long error message.",
    "created_at": "2013-04-25T12:53:54Z",
    "issue": "https://github.com/sagemath/sage/issues/14483",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/14483#issuecomment-177415",
    "user": "https://github.com/jdemeyer"
}
```

<a id='comment:14'></a>
I agree with Volker that a long warning is better than a long error message.



---

archive/issue_comments_177416.json:
```json
{
    "body": "<a id='comment:15'></a>\nOkayyyyyyyyyyyyyyyy....",
    "created_at": "2013-04-25T15:39:36Z",
    "issue": "https://github.com/sagemath/sage/issues/14483",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/14483#issuecomment-177416",
    "user": "https://github.com/nathanncohen"
}
```

<a id='comment:15'></a>
Okayyyyyyyyyyyyyyyy....



---

archive/issue_comments_177417.json:
```json
{
    "body": "<a id='comment:16'></a>\nWhat do you think of this ? Honestly I preferred the previous version... A warning just before an exception does not stand out at all ... `:-/`\n\nNathann",
    "created_at": "2013-04-25T15:54:26Z",
    "issue": "https://github.com/sagemath/sage/issues/14483",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/14483#issuecomment-177417",
    "user": "https://github.com/nathanncohen"
}
```

<a id='comment:16'></a>
What do you think of this ? Honestly I preferred the previous version... A warning just before an exception does not stand out at all ... `:-/`

Nathann



---

archive/issue_events_126716.json:
```json
{
    "actor": "https://github.com/nathanncohen",
    "created_at": "2013-04-25T15:54:31Z",
    "event": "unlabeled",
    "issue": "https://github.com/sagemath/sage/issues/14483",
    "label": "needs work",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/14483#event-126716"
}
```



---

archive/issue_events_126717.json:
```json
{
    "actor": "https://github.com/nathanncohen",
    "created_at": "2013-04-25T15:54:31Z",
    "event": "labeled",
    "issue": "https://github.com/sagemath/sage/issues/14483",
    "label": "needs review",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/14483#event-126717"
}
```



---

archive/issue_comments_177418.json:
```json
{
    "body": "<a id='comment:18'></a>\n\n```\nsage -t devel/sage/sage/groups/perm_gps/permgroup.py    \n**********************************************************************\nFile \"/Applications/sage/devel/sage/sage/groups/perm_gps/permgroup.py\", line 152:\n    sage: sage.groups.perm_gps.permgroup.load_hap()\nException raised:\n    Traceback (most recent call last):\n      File \"/Applications/sage/local/bin/ncadoctest.py\", line 1231, in run_one_test\n        self.run_one_example(test, example, filename, compileflags)\n      File \"/Applications/sage/local/bin/sagedoctest.py\", line 38, in run_one_example\n        OrigDocTestRunner.run_one_example(self, test, example, filename, compileflags)\n      File \"/Applications/sage/local/bin/ncadoctest.py\", line 1172, in run_one_example\n        compileflags, 1) in test.globs\n      File \"<doctest __main__.example_1[2]>\", line 1, in <module>\n        sage.groups.perm_gps.permgroup.load_hap()###line 152:\n    sage: sage.groups.perm_gps.permgroup.load_hap()\n      File \"/Applications/sage/local/lib/python/site-packages/sage/groups/perm_gps/permgroup.py\", line 157, in load_hap\n        gap.load_package(\"hap\")\n      File \"/Applications/sage/local/lib/python/site-packages/sage/interfaces/gap.py\", line 511, in load_package\n        raise RuntimeError('Error loading Gap package %s'%pkg)\n    RuntimeError: Error loading Gap package hap\n**********************************************************************\n```",
    "created_at": "2013-04-28T02:07:06Z",
    "issue": "https://github.com/sagemath/sage/issues/14483",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/14483#issuecomment-177418",
    "user": "https://github.com/jeffpferreira"
}
```

<a id='comment:18'></a>

```
sage -t devel/sage/sage/groups/perm_gps/permgroup.py    
**********************************************************************
File "/Applications/sage/devel/sage/sage/groups/perm_gps/permgroup.py", line 152:
    sage: sage.groups.perm_gps.permgroup.load_hap()
Exception raised:
    Traceback (most recent call last):
      File "/Applications/sage/local/bin/ncadoctest.py", line 1231, in run_one_test
        self.run_one_example(test, example, filename, compileflags)
      File "/Applications/sage/local/bin/sagedoctest.py", line 38, in run_one_example
        OrigDocTestRunner.run_one_example(self, test, example, filename, compileflags)
      File "/Applications/sage/local/bin/ncadoctest.py", line 1172, in run_one_example
        compileflags, 1) in test.globs
      File "<doctest __main__.example_1[2]>", line 1, in <module>
        sage.groups.perm_gps.permgroup.load_hap()###line 152:
    sage: sage.groups.perm_gps.permgroup.load_hap()
      File "/Applications/sage/local/lib/python/site-packages/sage/groups/perm_gps/permgroup.py", line 157, in load_hap
        gap.load_package("hap")
      File "/Applications/sage/local/lib/python/site-packages/sage/interfaces/gap.py", line 511, in load_package
        raise RuntimeError('Error loading Gap package %s'%pkg)
    RuntimeError: Error loading Gap package hap
**********************************************************************
```



---

archive/issue_events_126718.json:
```json
{
    "actor": "https://github.com/jeffpferreira",
    "created_at": "2013-04-28T02:07:06Z",
    "event": "unlabeled",
    "issue": "https://github.com/sagemath/sage/issues/14483",
    "label": "needs review",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/14483#event-126718"
}
```



---

archive/issue_events_126719.json:
```json
{
    "actor": "https://github.com/jeffpferreira",
    "created_at": "2013-04-28T02:07:06Z",
    "event": "labeled",
    "issue": "https://github.com/sagemath/sage/issues/14483",
    "label": "needs work",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/14483#event-126719"
}
```



---

archive/issue_comments_177419.json:
```json
{
    "body": "<a id='comment:19'></a>\nFixed ! What do you think of this warning/exception thing, by the way ?\n\nNathann",
    "created_at": "2013-04-28T08:10:54Z",
    "issue": "https://github.com/sagemath/sage/issues/14483",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/14483#issuecomment-177419",
    "user": "https://github.com/nathanncohen"
}
```

<a id='comment:19'></a>
Fixed ! What do you think of this warning/exception thing, by the way ?

Nathann



---

archive/issue_events_126720.json:
```json
{
    "actor": "https://github.com/nathanncohen",
    "created_at": "2013-04-28T08:10:54Z",
    "event": "unlabeled",
    "issue": "https://github.com/sagemath/sage/issues/14483",
    "label": "needs work",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/14483#event-126720"
}
```



---

archive/issue_events_126721.json:
```json
{
    "actor": "https://github.com/nathanncohen",
    "created_at": "2013-04-28T08:10:54Z",
    "event": "labeled",
    "issue": "https://github.com/sagemath/sage/issues/14483",
    "label": "needs review",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/14483#event-126721"
}
```



---

archive/issue_comments_177420.json:
```json
{
    "body": "<a id='comment:20'></a>\nI'm pretty sure the doctest will fail if you happen to have gap_packages installed (which includes HAP). How about we use `gap.load_package(\"foobar\")` or something like that instead?",
    "created_at": "2013-04-28T10:40:50Z",
    "issue": "https://github.com/sagemath/sage/issues/14483",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/14483#issuecomment-177420",
    "user": "https://github.com/vbraun"
}
```

<a id='comment:20'></a>
I'm pretty sure the doctest will fail if you happen to have gap_packages installed (which includes HAP). How about we use `gap.load_package("foobar")` or something like that instead?



---

archive/issue_comments_177421.json:
```json
{
    "body": "<a id='comment:21'></a>\nSuch a doctest already exists in `interfaces/gap.py`. Do you think that we should remove this doctest from `permgroup.py` ? I think it make sense.\n\nWhat do you think of this warning/exception thing ?\n\nNathann",
    "created_at": "2013-04-28T10:45:51Z",
    "issue": "https://github.com/sagemath/sage/issues/14483",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/14483#issuecomment-177421",
    "user": "https://github.com/nathanncohen"
}
```

<a id='comment:21'></a>
Such a doctest already exists in `interfaces/gap.py`. Do you think that we should remove this doctest from `permgroup.py` ? I think it make sense.

What do you think of this warning/exception thing ?

Nathann



---

archive/issue_comments_177422.json:
```json
{
    "body": "<a id='comment:22'></a>\nThe doctest for the `load_package()` isn't necessary if it is tested elsewhere, but it is the natural place in the docstring to point out that you have to install HAP. I'll let you decide if you want to keep it or not.\n\nAs I said already, helpful explanations should be warnings not errors. The error message should be less than a whole line if possible. Advanced users shouldn't be drowned in paragraphs of text for simple errors. We could make warnings more prominent (say, using colors or bold text), but thats for another ticket.",
    "created_at": "2013-04-28T11:22:36Z",
    "issue": "https://github.com/sagemath/sage/issues/14483",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/14483#issuecomment-177422",
    "user": "https://github.com/vbraun"
}
```

<a id='comment:22'></a>
The doctest for the `load_package()` isn't necessary if it is tested elsewhere, but it is the natural place in the docstring to point out that you have to install HAP. I'll let you decide if you want to keep it or not.

As I said already, helpful explanations should be warnings not errors. The error message should be less than a whole line if possible. Advanced users shouldn't be drowned in paragraphs of text for simple errors. We could make warnings more prominent (say, using colors or bold text), but thats for another ticket.



---

archive/issue_comments_177423.json:
```json
{
    "body": "<a id='comment:23'></a>\nThen I will probaly remove the doctest.\n\nMy problem with exceptions and warnings is not so general : in that case, a warning is printed just before the exception is raised, and no one sees the warning as a result. It would make more sense to just raise an exception. I will try to make the error message shorter.\n\nNathann",
    "created_at": "2013-04-28T11:27:24Z",
    "issue": "https://github.com/sagemath/sage/issues/14483",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/14483#issuecomment-177423",
    "user": "https://github.com/nathanncohen"
}
```

<a id='comment:23'></a>
Then I will probaly remove the doctest.

My problem with exceptions and warnings is not so general : in that case, a warning is printed just before the exception is raised, and no one sees the warning as a result. It would make more sense to just raise an exception. I will try to make the error message shorter.

Nathann



---

archive/attachments_020214.json:
```json
{
    "asset_content_type": "application/octet-stream",
    "asset_name": "trac_14483.patch",
    "asset_url": "tarball://root/attachments/ticket14483/trac_14483.patch",
    "created_at": "2013-04-28T13:41:49Z",
    "issue": "https://github.com/sagemath/sage/issues/14483",
    "type": "attachment",
    "url": "https://github.com/sagemath/sage/files/ticket14483/trac_14483.patch",
    "user": "https://github.com/nathanncohen"
}
```



---

archive/issue_comments_177424.json:
```json
{
    "body": "<a id='comment:24'></a>\n**Attachment:** [trac_14483.patch](https://github.com/sagemath/sage/files/ticket14483/trac_14483.patch)\n\nWhat about this ?\n\nNathann",
    "created_at": "2013-04-28T13:41:49Z",
    "issue": "https://github.com/sagemath/sage/issues/14483",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/14483#issuecomment-177424",
    "user": "https://github.com/nathanncohen"
}
```

<a id='comment:24'></a>
**Attachment:** [trac_14483.patch](https://github.com/sagemath/sage/files/ticket14483/trac_14483.patch)

What about this ?

Nathann



---

archive/issue_events_126722.json:
```json
{
    "actor": "https://github.com/vbraun",
    "created_at": "2013-04-28T14:22:49Z",
    "event": "unlabeled",
    "issue": "https://github.com/sagemath/sage/issues/14483",
    "label": "needs review",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/14483#event-126722"
}
```



---

archive/issue_events_126723.json:
```json
{
    "actor": "https://github.com/vbraun",
    "created_at": "2013-04-28T14:22:49Z",
    "event": "labeled",
    "issue": "https://github.com/sagemath/sage/issues/14483",
    "label": "positive review",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/14483#event-126723"
}
```



---

archive/issue_comments_177425.json:
```json
{
    "body": "<a id='comment:25'></a>\nFine with me.",
    "created_at": "2013-04-28T14:22:49Z",
    "issue": "https://github.com/sagemath/sage/issues/14483",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/14483#issuecomment-177425",
    "user": "https://github.com/vbraun"
}
```

<a id='comment:25'></a>
Fine with me.



---

archive/issue_events_126724.json:
```json
{
    "actor": "https://github.com/jdemeyer",
    "created_at": "2013-04-30T09:40:18Z",
    "event": "unlabeled",
    "issue": "https://github.com/sagemath/sage/issues/14483",
    "label": "positive review",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/14483#event-126724"
}
```



---

archive/issue_events_126725.json:
```json
{
    "actor": "https://github.com/jdemeyer",
    "created_at": "2013-04-30T09:40:18Z",
    "event": "closed",
    "issue": "https://github.com/sagemath/sage/issues/14483",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/14483#event-126725"
}
```



---

archive/issue_comments_177426.json:
```json
{
    "body": "**Merged:** sage-5.10.beta1",
    "created_at": "2013-04-30T09:40:18Z",
    "issue": "https://github.com/sagemath/sage/issues/14483",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/14483#issuecomment-177426",
    "user": "https://github.com/jdemeyer"
}
```

**Merged:** sage-5.10.beta1
