# Issue 28738: Docker SageMath install fails

archive/issues_028501.json:
```json
{
    "body": "See https://gitlab.com/sagemath/sage/-/jobs/346689490#L2328\n\n```\n2328 Step 61/66 : RUN sudo $SAGE_ROOT/sage --nodotsage -c \"install_scripts('/usr/bin')\"\n2329  ---> Running in 1751eed7188f\n2330 /home/sage/sage/build/bin/sage-system-python: line 24: exec: : not found\n```\n\nDepends on #29090\n\n**CC:**  @embray @slel\n\n**Keywords:** docker, ci\n\n**Branch:** [u/saraedum/docker-runtime-sage](https://github.com/sagemath/sagetrac-mirror/tree/u/saraedum/docker-runtime-sage)\n\n**Commit:** [93152407ae99d9bcaa2c88218aa3397098fd0ffb](https://github.com/sagemath/sagetrac-mirror/commit/93152407ae99d9bcaa2c88218aa3397098fd0ffb)\n\nIssue created by migration from https://trac.sagemath.org/ticket/28738\n\n",
    "closed_at": "2020-09-15T16:00:52Z",
    "created_at": "2019-11-14T18:41:27Z",
    "labels": [
        "component: docker",
        "bug",
        "duplicate"
    ],
    "title": "Docker SageMath install fails",
    "type": "issue",
    "url": "https://github.com/sagemath/sage/issues/28738",
    "user": "https://github.com/saraedum"
}
```
See https://gitlab.com/sagemath/sage/-/jobs/346689490#L2328

```
2328 Step 61/66 : RUN sudo $SAGE_ROOT/sage --nodotsage -c "install_scripts('/usr/bin')"
2329  ---> Running in 1751eed7188f
2330 /home/sage/sage/build/bin/sage-system-python: line 24: exec: : not found
```

Depends on #29090

**CC:**  @embray @slel

**Keywords:** docker, ci

**Branch:** [u/saraedum/docker-runtime-sage](https://github.com/sagemath/sagetrac-mirror/tree/u/saraedum/docker-runtime-sage)

**Commit:** [93152407ae99d9bcaa2c88218aa3397098fd0ffb](https://github.com/sagemath/sagetrac-mirror/commit/93152407ae99d9bcaa2c88218aa3397098fd0ffb)

Issue created by migration from https://trac.sagemath.org/ticket/28738





---

archive/issue_comments_451046.json:
```json
{
    "body": "<a id='comment:1'></a>\nI have not checked what's causing this but Python 2 builds fail with this error.",
    "created_at": "2019-11-14T18:42:09Z",
    "issue": "https://github.com/sagemath/sage/issues/28738",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/28738#issuecomment-451046",
    "user": "https://github.com/saraedum"
}
```

<a id='comment:1'></a>
I have not checked what's causing this but Python 2 builds fail with this error.



---

archive/issue_comments_451047.json:
```json
{
    "body": "<a id='comment:2'></a>\nIt would appear that `sage-system-python` is, well, not finding the system python.  Far less clear is why that command would seem to be invoking `sage-system-python` in the first place...",
    "created_at": "2019-11-15T11:53:50Z",
    "issue": "https://github.com/sagemath/sage/issues/28738",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/28738#issuecomment-451047",
    "user": "https://github.com/embray"
}
```

<a id='comment:2'></a>
It would appear that `sage-system-python` is, well, not finding the system python.  Far less clear is why that command would seem to be invoking `sage-system-python` in the first place...



---

archive/issue_comments_451048.json:
```json
{
    "body": "<a id='comment:3'></a>\nFWIW I was able to reproduce the problem locally, no problem.  But I haven't looked into what's causing it yet.",
    "created_at": "2019-11-15T16:18:50Z",
    "issue": "https://github.com/sagemath/sage/issues/28738",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/28738#issuecomment-451048",
    "user": "https://github.com/embray"
}
```

<a id='comment:3'></a>
FWIW I was able to reproduce the problem locally, no problem.  But I haven't looked into what's causing it yet.



---

archive/issue_comments_451049.json:
```json
{
    "body": "<a id='comment:4'></a>\nI see now.  Just recently (which is why I didn't see this at first; I hadn't pulled this update locally) in #28657 the `sage-location` script was changed to use `sage-system-python`, and `sage-location` is called by the main `sage` script.\n\nI'm not sure yet exactly why this change was made but it should be perfectly possible to work around.",
    "created_at": "2019-11-15T16:32:22Z",
    "issue": "https://github.com/sagemath/sage/issues/28738",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/28738#issuecomment-451049",
    "user": "https://github.com/embray"
}
```

<a id='comment:4'></a>
I see now.  Just recently (which is why I didn't see this at first; I hadn't pulled this update locally) in #28657 the `sage-location` script was changed to use `sage-system-python`, and `sage-location` is called by the main `sage` script.

I'm not sure yet exactly why this change was made but it should be perfectly possible to work around.



---

archive/issue_comments_451050.json:
```json
{
    "body": "**Changing keywords** from \"\" to \"docker, ci\".",
    "created_at": "2019-11-17T21:41:06Z",
    "issue": "https://github.com/sagemath/sage/issues/28738",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/28738#issuecomment-451050",
    "user": "https://github.com/saraedum"
}
```

**Changing keywords** from "" to "docker, ci".



---

archive/issue_comments_451051.json:
```json
{
    "body": "**Branch:** [u/saraedum/docker-runtime-sage](https://github.com/sagemath/sagetrac-mirror/tree/u/saraedum/docker-runtime-sage)",
    "created_at": "2019-11-17T21:53:02Z",
    "issue": "https://github.com/sagemath/sage/issues/28738",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/28738#issuecomment-451051",
    "user": "https://github.com/saraedum"
}
```

**Branch:** [u/saraedum/docker-runtime-sage](https://github.com/sagemath/sagetrac-mirror/tree/u/saraedum/docker-runtime-sage)



---

archive/issue_comments_451052.json:
```json
{
    "body": "<a id='comment:7'></a>\nI'm now installing Python as a runtime dependency. Not sure that's the best way to fix this; I asked on #28657.\n\n---\n**New commits:**\n<table><tr><td><a href=\"https://github.com/sagemath/sagetrac-mirror/commit/93152407ae99d9bcaa2c88218aa3397098fd0ffb\">9315240</a></td><td><code>SageMath now requires system Python to be available at runtime</code></td></tr></table>\n",
    "created_at": "2019-11-17T22:03:27Z",
    "issue": "https://github.com/sagemath/sage/issues/28738",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/28738#issuecomment-451052",
    "user": "https://github.com/saraedum"
}
```

<a id='comment:7'></a>
I'm now installing Python as a runtime dependency. Not sure that's the best way to fix this; I asked on #28657.

---
**New commits:**
<table><tr><td><a href="https://github.com/sagemath/sagetrac-mirror/commit/93152407ae99d9bcaa2c88218aa3397098fd0ffb">9315240</a></td><td><code>SageMath now requires system Python to be available at runtime</code></td></tr></table>




---

archive/issue_comments_451053.json:
```json
{
    "body": "**Commit:** [93152407ae99d9bcaa2c88218aa3397098fd0ffb](https://github.com/sagemath/sagetrac-mirror/commit/93152407ae99d9bcaa2c88218aa3397098fd0ffb)",
    "created_at": "2019-11-17T22:03:27Z",
    "issue": "https://github.com/sagemath/sage/issues/28738",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/28738#issuecomment-451053",
    "user": "https://github.com/saraedum"
}
```

**Commit:** [93152407ae99d9bcaa2c88218aa3397098fd0ffb](https://github.com/sagemath/sagetrac-mirror/commit/93152407ae99d9bcaa2c88218aa3397098fd0ffb)



---

archive/issue_comments_451054.json:
```json
{
    "body": "<a id='comment:8'></a>\nReplying to [@embray](#comment%3A4):\n> I see now.  Just recently (which is why I didn't see this at first; I hadn't pulled this update locally) in #28657 the `sage-location` script was changed to use `sage-system-python`, and `sage-location` is called by the main `sage` script.\n> \n> I'm not sure yet exactly why this change was made but it should be perfectly possible to work around.\n\nThe change is explained in #28657: on some systems, for example the latest releases of Ubuntu, there is no `python` executable, just `python3`. On top of that, in a Python 3 build of Sage, we don't create a `python` executable. So we shouldn't expect `#!/usr/bin/env python` to work.\n\nIt sounds like `sage-system-python` is not robust enough, if it's not handling this situation.",
    "created_at": "2019-11-18T01:08:34Z",
    "issue": "https://github.com/sagemath/sage/issues/28738",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/28738#issuecomment-451054",
    "user": "https://github.com/jhpalmieri"
}
```

<a id='comment:8'></a>
Replying to [@embray](#comment%3A4):
> I see now.  Just recently (which is why I didn't see this at first; I hadn't pulled this update locally) in #28657 the `sage-location` script was changed to use `sage-system-python`, and `sage-location` is called by the main `sage` script.
> 
> I'm not sure yet exactly why this change was made but it should be perfectly possible to work around.

The change is explained in #28657: on some systems, for example the latest releases of Ubuntu, there is no `python` executable, just `python3`. On top of that, in a Python 3 build of Sage, we don't create a `python` executable. So we shouldn't expect `#!/usr/bin/env python` to work.

It sounds like `sage-system-python` is not robust enough, if it's not handling this situation.



---

archive/issue_comments_451055.json:
```json
{
    "body": "<a id='comment:9'></a>\nOr `sage-location` should be able to use Sage's Python, if that's the only one available. Are there really systems with neither `python` nor `python3` on which Sage is expected to run?",
    "created_at": "2019-11-18T01:10:27Z",
    "issue": "https://github.com/sagemath/sage/issues/28738",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/28738#issuecomment-451055",
    "user": "https://github.com/jhpalmieri"
}
```

<a id='comment:9'></a>
Or `sage-location` should be able to use Sage's Python, if that's the only one available. Are there really systems with neither `python` nor `python3` on which Sage is expected to run?



---

archive/issue_comments_451056.json:
```json
{
    "body": "<a id='comment:10'></a>\nReplying to [@jhpalmieri](#comment%3A9):\n> Or `sage-location` should be able to use Sage's Python, if that's the only one available. Are there really systems with neither `python` nor `python3` on which Sage is expected to run?\n\nThe [SageMath](../wiki/SageMath) download page at least does not say that you need Python.\n\nIs Python pre-installed on Windows these days?\n\nIt comes pre-installed on macOS, but that's bound to change I think:\n\n> Scripting language runtimes such as Python, Ruby, and Perl are included in macOS for compatibility with legacy software. In future versions of macOS, scripting language runtimes won\u2019t be available by default, and may require you to install an additional package. If your software depends on scripting languages, it\u2019s recommended that you bundle the runtime within the app. (49764202)",
    "created_at": "2019-11-18T11:05:59Z",
    "issue": "https://github.com/sagemath/sage/issues/28738",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/28738#issuecomment-451056",
    "user": "https://github.com/saraedum"
}
```

<a id='comment:10'></a>
Replying to [@jhpalmieri](#comment%3A9):
> Or `sage-location` should be able to use Sage's Python, if that's the only one available. Are there really systems with neither `python` nor `python3` on which Sage is expected to run?

The [SageMath](../wiki/SageMath) download page at least does not say that you need Python.

Is Python pre-installed on Windows these days?

It comes pre-installed on macOS, but that's bound to change I think:

> Scripting language runtimes such as Python, Ruby, and Perl are included in macOS for compatibility with legacy software. In future versions of macOS, scripting language runtimes won’t be available by default, and may require you to install an additional package. If your software depends on scripting languages, it’s recommended that you bundle the runtime within the app. (49764202)



---

archive/issue_comments_451057.json:
```json
{
    "body": "<a id='comment:11'></a>\nTicket retargeted after milestone closed",
    "created_at": "2020-01-06T14:10:03Z",
    "issue": "https://github.com/sagemath/sage/issues/28738",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/28738#issuecomment-451057",
    "user": "https://github.com/embray"
}
```

<a id='comment:11'></a>
Ticket retargeted after milestone closed



---

archive/issue_events_257207.json:
```json
{
    "actor": "https://github.com/embray",
    "created_at": "2020-01-06T14:10:03Z",
    "event": "demilestoned",
    "issue": "https://github.com/sagemath/sage/issues/28738",
    "milestone": "sage-9.0",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/28738#event-257207"
}
```



---

archive/issue_events_257208.json:
```json
{
    "actor": "https://github.com/embray",
    "created_at": "2020-01-06T14:10:03Z",
    "event": "milestoned",
    "issue": "https://github.com/sagemath/sage/issues/28738",
    "milestone": "sage-9.1",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/28738#event-257208"
}
```



---

archive/issue_comments_451058.json:
```json
{
    "body": "<a id='comment:12'></a>\nSee also #29090 - \"configure forgets to check whether ANY Python is available on the system\"",
    "created_at": "2020-03-17T23:18:41Z",
    "issue": "https://github.com/sagemath/sage/issues/28738",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/28738#issuecomment-451058",
    "user": "https://github.com/mkoeppe"
}
```

<a id='comment:12'></a>
See also #29090 - "configure forgets to check whether ANY Python is available on the system"



---

archive/issue_comments_451059.json:
```json
{
    "body": "<a id='comment:13'></a>\nFixed by #29090.",
    "created_at": "2020-03-18T01:44:34Z",
    "issue": "https://github.com/sagemath/sage/issues/28738",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/28738#issuecomment-451059",
    "user": "https://github.com/mkoeppe"
}
```

<a id='comment:13'></a>
Fixed by #29090.



---

archive/issue_comments_451060.json:
```json
{
    "body": "**Dependencies:** #29090",
    "created_at": "2020-03-18T02:47:31Z",
    "issue": "https://github.com/sagemath/sage/issues/28738",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/28738#issuecomment-451060",
    "user": "https://github.com/mkoeppe"
}
```

**Dependencies:** #29090



---

archive/issue_events_257209.json:
```json
{
    "actor": "https://github.com/mkoeppe",
    "created_at": "2020-05-07T02:57:56Z",
    "event": "demilestoned",
    "issue": "https://github.com/sagemath/sage/issues/28738",
    "milestone": "sage-9.1",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/28738#event-257209"
}
```



---

archive/issue_events_257210.json:
```json
{
    "actor": "https://github.com/mkoeppe",
    "created_at": "2020-05-07T02:57:56Z",
    "event": "labeled",
    "issue": "https://github.com/sagemath/sage/issues/28738",
    "label": "needs review",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/28738#event-257210"
}
```



---

archive/issue_events_257211.json:
```json
{
    "actor": "https://github.com/fchapoton",
    "created_at": "2020-09-15T16:00:52Z",
    "event": "labeled",
    "issue": "https://github.com/sagemath/sage/issues/28738",
    "label": "duplicate",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/28738#event-257211"
}
```



---

archive/issue_events_257212.json:
```json
{
    "actor": "https://github.com/fchapoton",
    "created_at": "2020-09-15T16:00:52Z",
    "event": "unlabeled",
    "issue": "https://github.com/sagemath/sage/issues/28738",
    "label": "needs review",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/28738#event-257212"
}
```



---

archive/issue_events_257213.json:
```json
{
    "actor": "https://github.com/fchapoton",
    "created_at": "2020-09-15T16:00:52Z",
    "event": "closed",
    "issue": "https://github.com/sagemath/sage/issues/28738",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/28738#event-257213"
}
```
