# Issue 13792: sagenb.notebook.worksheet.Worksheet( and <tab> gives error

archive/issues_013588.json:
```json
{
    "body": "Just saying \"sagenb.notebook.worksheet.Worksheet(\" and pressing <tab> gives\n\nTraceback (most recent call last): File \"\", line 1, in File                     \n\"_sage_input_3.py\", line 10, in exec compile(u'print                            \n_support_.docstring(\"sagenb.notebook.worksheet.Worksheet\", globals(),           \nsystem=\"sage\")' + '\\n', '', 'single') File \"\", line 1, in File                  \n\"/path/to/sage-5.4/devel/sagenb-ldap/sagenb/misc/support.py\", line 275,         \nin docstring return html_markup(s.decode('utf-8')) File                         \n\"/path/to/sage-5.4/devel/sagenb-ldap/sagenb/misc/support.py\", line 280,         \nin html_markup return sphinxify(s) File                                         \n\"/path/to/sage-5.4/devel/sagenb-ldap/sagenb/misc/sphinxify.py\", line            \n79, in sphinxify filed.write(docstring) UnicodeEncodeError: 'ascii' codec       \ncan't encode characters in position 1476-1486: ordinal not in range(128)\n\n\n**Assignee:** @jasongrout, @qed777, @williamstein\n\n**Reviewer:** Karl-Dieter Crisman, Jori M\u00e4ntysalo\n\nIssue created by migration from https://trac.sagemath.org/ticket/13792\n\n",
    "closed_at": "2013-08-13T08:35:18Z",
    "created_at": "2012-12-03T11:52:33Z",
    "labels": [
        "component: notebook",
        "trivial",
        "bug",
        "worksforme",
        "invalid"
    ],
    "title": "sagenb.notebook.worksheet.Worksheet( and <tab> gives error",
    "type": "issue",
    "url": "https://github.com/sagemath/sage/issues/13792",
    "user": "https://github.com/jm58660"
}
```
Just saying "sagenb.notebook.worksheet.Worksheet(" and pressing <tab> gives

Traceback (most recent call last): File "", line 1, in File                     
"_sage_input_3.py", line 10, in exec compile(u'print                            
_support_.docstring("sagenb.notebook.worksheet.Worksheet", globals(),           
system="sage")' + '\n', '', 'single') File "", line 1, in File                  
"/path/to/sage-5.4/devel/sagenb-ldap/sagenb/misc/support.py", line 275,         
in docstring return html_markup(s.decode('utf-8')) File                         
"/path/to/sage-5.4/devel/sagenb-ldap/sagenb/misc/support.py", line 280,         
in html_markup return sphinxify(s) File                                         
"/path/to/sage-5.4/devel/sagenb-ldap/sagenb/misc/sphinxify.py", line            
79, in sphinxify filed.write(docstring) UnicodeEncodeError: 'ascii' codec       
can't encode characters in position 1476-1486: ordinal not in range(128)


**Assignee:** @jasongrout, @qed777, @williamstein

**Reviewer:** Karl-Dieter Crisman, Jori Mäntysalo

Issue created by migration from https://trac.sagemath.org/ticket/13792





---

archive/issue_events_119011.json:
```json
{
    "actor": "https://github.com/kcrisman",
    "created_at": "2013-06-14T19:59:32Z",
    "event": "labeled",
    "issue": "https://github.com/sagemath/sage/issues/13792",
    "label": "needs info",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/13792#event-119011"
}
```



---

archive/issue_comments_164812.json:
```json
{
    "body": "<a id='comment:1'></a>\nI'm not getting this in Sage 5.2 or 5.6 *or* 5.9+#14330.  Can you give more details about the situation?  Maybe this is related to your using an incomplete ldap version of sagenb.",
    "created_at": "2013-06-14T19:59:32Z",
    "issue": "https://github.com/sagemath/sage/issues/13792",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/13792#issuecomment-164812",
    "user": "https://github.com/kcrisman"
}
```

<a id='comment:1'></a>
I'm not getting this in Sage 5.2 or 5.6 *or* 5.9+#14330.  Can you give more details about the situation?  Maybe this is related to your using an incomplete ldap version of sagenb.



---

archive/issue_events_119012.json:
```json
{
    "actor": "https://github.com/kcrisman",
    "created_at": "2013-06-14T19:59:40Z",
    "event": "labeled",
    "issue": "https://github.com/sagemath/sage/issues/13792",
    "label": "bug",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/13792#event-119012"
}
```



---

archive/issue_comments_164813.json:
```json
{
    "body": "<a id='comment:3'></a>\nReplying to [@kcrisman](#comment%3A1):\n\n> I'm not getting this in Sage 5.2 or 5.6 *or* 5.9+#14330.\n\nI just tested with plain 5.10 and this bug does not occurred. So it must have been something with ldap or some additional package. I guess this one can be closed.",
    "created_at": "2013-07-02T10:08:32Z",
    "issue": "https://github.com/sagemath/sage/issues/13792",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/13792#issuecomment-164813",
    "user": "https://github.com/jm58660"
}
```

<a id='comment:3'></a>
Replying to [@kcrisman](#comment%3A1):

> I'm not getting this in Sage 5.2 or 5.6 *or* 5.9+#14330.

I just tested with plain 5.10 and this bug does not occurred. So it must have been something with ldap or some additional package. I guess this one can be closed.



---

archive/issue_comments_164814.json:
```json
{
    "body": "**Reviewer:** Karl-Dieter Crisman, Jori M\u00e4ntysalo",
    "created_at": "2013-07-02T13:46:52Z",
    "issue": "https://github.com/sagemath/sage/issues/13792",
    "type": "issue_comment",
    "url": "https://github.com/sagemath/sage/issues/13792#issuecomment-164814",
    "user": "https://github.com/kcrisman"
}
```

**Reviewer:** Karl-Dieter Crisman, Jori Mäntysalo



---

archive/issue_events_119013.json:
```json
{
    "actor": "https://github.com/kcrisman",
    "created_at": "2013-07-02T13:46:52Z",
    "event": "unlabeled",
    "issue": "https://github.com/sagemath/sage/issues/13792",
    "label": "needs info",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/13792#event-119013"
}
```



---

archive/issue_events_119014.json:
```json
{
    "actor": "https://github.com/kcrisman",
    "created_at": "2013-07-02T13:46:52Z",
    "event": "labeled",
    "issue": "https://github.com/sagemath/sage/issues/13792",
    "label": "needs review",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/13792#event-119014"
}
```



---

archive/issue_events_119015.json:
```json
{
    "actor": "https://github.com/kcrisman",
    "created_at": "2013-07-02T13:47:00Z",
    "event": "unlabeled",
    "issue": "https://github.com/sagemath/sage/issues/13792",
    "label": "needs review",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/13792#event-119015"
}
```



---

archive/issue_events_119016.json:
```json
{
    "actor": "https://github.com/kcrisman",
    "created_at": "2013-07-02T13:47:00Z",
    "event": "labeled",
    "issue": "https://github.com/sagemath/sage/issues/13792",
    "label": "positive review",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/13792#event-119016"
}
```



---

archive/issue_events_119017.json:
```json
{
    "actor": "https://github.com/jdemeyer",
    "created_at": "2013-08-13T08:35:18Z",
    "event": "labeled",
    "issue": "https://github.com/sagemath/sage/issues/13792",
    "label": "worksforme",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/13792#event-119017"
}
```



---

archive/issue_events_119018.json:
```json
{
    "actor": "https://github.com/jdemeyer",
    "created_at": "2013-08-13T08:35:18Z",
    "event": "unlabeled",
    "issue": "https://github.com/sagemath/sage/issues/13792",
    "label": "positive review",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/13792#event-119018"
}
```



---

archive/issue_events_119019.json:
```json
{
    "actor": "https://github.com/jdemeyer",
    "created_at": "2013-08-13T08:35:18Z",
    "event": "closed",
    "issue": "https://github.com/sagemath/sage/issues/13792",
    "type": "issue_event",
    "url": "https://github.com/sagemath/sage/issues/13792#event-119019"
}
```
